// SPDX-License-Identifier: AGPL-3.0-or-later
//! The generated ADR Overview (SAS §19.6, Appendix A, RQ-021).
//!
//! §19.7: "No manual ADR index." This document is a projection of the ADR atoms
//! and is never edited — the same rule that governs a Warrant's parent, for the
//! same reason. A hand-maintained index drifts from its sources, and an index
//! that disagrees with the decisions it lists is worse than no index, because
//! people trust it.

use std::fmt::Write as _;

use openwarrant_core::adr::AdrRecord;

/// The Appendix A sections, in order.
const SECTIONS: [&str; 4] = [
    "Proposed",
    "Accepted and Current",
    "Superseded",
    "Rejected, Withdrawn, or Falsified",
];

/// Render the ADR Overview.
///
/// `records` are sorted by local alias so the output is a pure function of the
/// set, not of the order the filesystem happened to yield.
pub fn render(records: &[AdrRecord]) -> String {
    let mut sorted: Vec<&AdrRecord> = records.iter().collect();
    sorted.sort_by(|a, b| a.local_alias.cmp(&b.local_alias));

    let mut out = String::new();
    out.push_str(
        "<!--\nGENERATED BY OPENWARRANT. DO NOT EDIT.\nSource: ADR atoms under the configured adrs path.\n-->\n\n",
    );
    out.push_str("# Architecture Decision Record Overview\n\n");

    if sorted.is_empty() {
        out.push_str("No architecture decisions are recorded yet.\n");
        return out;
    }

    out.push_str("## Summary\n\n");
    out.push_str("| ADR | Title | Status | Current | Governs |\n");
    out.push_str("|---|---|---|---|---|\n");
    for adr in &sorted {
        let governs = if adr.governs.is_empty() {
            "—".to_owned()
        } else {
            adr.governs
                .iter()
                .map(|g| format!("`{g}`"))
                .collect::<Vec<_>>()
                .join("<br>")
        };
        let _ = writeln!(
            out,
            "| [{alias}]({source}) | {title} | `{status}` | {current} | {governs} |",
            alias = adr.local_alias,
            source = adr.source,
            title = adr.title,
            status = adr.status,
            current = if adr.status.is_current() { "yes" } else { "no" },
        );
    }

    // Lifecycle buckets. A section with no members is omitted rather than
    // rendered empty — the same rule §16.1 applies to a Warrant's parent.
    for section in SECTIONS {
        let members: Vec<&&AdrRecord> = sorted
            .iter()
            .filter(|a| a.status.overview_section() == section)
            .collect();
        if members.is_empty() {
            continue;
        }
        let _ = write!(out, "\n## {section}\n\n");
        for adr in members {
            let decided = adr
                .decided
                .as_deref()
                .map(|d| format!(" — {d}"))
                .unwrap_or_default();
            let _ = writeln!(out, "- **{}** {}{}", adr.local_alias, adr.title, decided);
        }
    }

    // §19.6: the overview "contains the complete ADR bodies concatenated into
    // one generated audit document." A summary table alone would make the
    // overview a second index rather than the audit record it is meant to be.
    out.push_str("\n---\n\n# Full Decision Record\n");
    for adr in &sorted {
        let _ = write!(out, "\n---\n\n");
        let _ = writeln!(
            out,
            "<!-- source: {} · uuid: {} -->\n",
            adr.source, adr.uuid
        );
        out.push_str(adr.body.trim_end());
        out.push('\n');
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use openwarrant_core::adr::AdrStatus;

    fn adr(alias: &str, title: &str, status: AdrStatus) -> AdrRecord {
        AdrRecord {
            uuid: format!("uuid-{alias}"),
            local_alias: alias.to_owned(),
            title: title.to_owned(),
            status,
            decided: Some("2026-08-19".to_owned()),
            governs: vec!["war://abc".to_owned()],
            body: format!("# {title}\n\nThe body of {alias}.\n"),
            source: format!("docs/adr/atoms/{alias}.md"),
            supersedes: vec![],
            superseded_by: None,
        }
    }

    #[test]
    fn renders_summary_buckets_and_full_bodies() {
        let records = vec![
            adr("OW-ADR-0001", "First decision", AdrStatus::Accepted),
            adr("OW-ADR-0002", "Second decision", AdrStatus::Proposed),
        ];
        let out = render(&records);

        assert!(out.starts_with("<!--\nGENERATED BY OPENWARRANT. DO NOT EDIT."));
        assert!(out.contains("## Summary"));
        assert!(out.contains("## Accepted and Current"));
        assert!(out.contains("## Proposed"));
        assert!(out.contains("# Full Decision Record"));
        // §19.6: complete bodies, not just an index.
        assert!(out.contains("The body of OW-ADR-0001."));
        assert!(out.contains("The body of OW-ADR-0002."));
    }

    /// An empty lifecycle bucket is omitted, not rendered as a bare heading.
    #[test]
    fn empty_sections_are_omitted() {
        let out = render(&[adr("OW-ADR-0001", "Only one", AdrStatus::Accepted)]);
        assert!(out.contains("## Accepted and Current"));
        assert!(!out.contains("## Proposed"));
        assert!(!out.contains("## Superseded"));
        assert!(!out.contains("## Rejected"));
    }

    /// Output must not depend on the order the filesystem yielded the atoms,
    /// or the drift check would fire on a directory re-read.
    #[test]
    fn output_is_independent_of_input_order() {
        let a = adr("OW-ADR-0001", "First", AdrStatus::Accepted);
        let b = adr("OW-ADR-0002", "Second", AdrStatus::Accepted);
        assert_eq!(
            render(&[a.clone(), b.clone()]),
            render(&[b, a]),
            "the overview is a function of the SET, not of iteration order"
        );
    }

    #[test]
    fn an_empty_corpus_says_so_rather_than_rendering_an_empty_table() {
        let out = render(&[]);
        assert!(out.contains("No architecture decisions are recorded yet."));
        assert!(!out.contains("| ADR |"));
    }

    #[test]
    fn currency_is_reported_per_adr() {
        let out = render(&[
            adr("OW-ADR-0001", "Live", AdrStatus::Accepted),
            adr("OW-ADR-0002", "Dead", AdrStatus::Superseded),
        ]);
        let accepted_row = out
            .lines()
            .find(|l| l.contains("OW-ADR-0001") && l.starts_with('|'))
            .expect("row");
        let superseded_row = out
            .lines()
            .find(|l| l.contains("OW-ADR-0002") && l.starts_with('|'))
            .expect("row");
        assert!(accepted_row.contains("| yes |"));
        assert!(superseded_row.contains("| no |"));
    }
}
