// SPDX-License-Identifier: AGPL-3.0-or-later
//! Render the corpus projection (SAS §17.5 `status`, corpus form).
//!
//! Two outputs from one value: Markdown for a person, RFC 8785 canonical JSON
//! for an agent. The JSON is the contract — a viewer, a Huly sync, a herdr
//! pane all read it and write nothing back (§77.3: consumers take generated
//! schemas; they do not reimplement WAR semantics).
//!
//! # No ratio, anywhere in this file
//!
//! Every number below is a rung count with the strictest rung first, or a
//! histogram of NAMES. `resolution.rs` says why: "'11 of 13' tells a reader
//! nothing about whether to worry." A percentage would be that sentence with
//! the 13 hidden.

use std::fmt::Write as _;

use openwarrant_core::status::{Achieved, CorpusStatus, Reached, Validity, WarrantRung};

use crate::canonical::{CanonicalError, to_canonical_string};

/// The canonical JSON an agent reads.
pub fn canonical_json(status: &CorpusStatus) -> Result<String, CanonicalError> {
    to_canonical_string(status)
}

fn rung_word(r: WarrantRung) -> &'static str {
    match r {
        WarrantRung::Invalid => "invalid",
        WarrantRung::Draft => "draft",
        WarrantRung::ReadyToResolve => "ready_to_resolve",
        WarrantRung::WouldSatisfy => "would_satisfy",
        WarrantRung::Resolved => "resolved",
    }
}

/// The Markdown a person reads.
pub fn render_markdown(status: &CorpusStatus) -> String {
    let mut out = String::new();
    out.push_str(
        "<!--\nGENERATED BY OPENWARRANT. DO NOT EDIT.\nSource: every Warrant under the configured warrants path, its sidecar records, and SAS §106.\n-->\n\n",
    );
    out.push_str("# Corpus Status\n\n");
    let _ = writeln!(
        out,
        "*Provenance: **{}**. {}*\n",
        status.provenance, status.provenance_note
    );

    if !status.caveats.is_empty() {
        out.push_str("## Read this first\n\n");
        for c in &status.caveats {
            let _ = writeln!(out, "- {c}");
        }
        out.push('\n');
    }

    // Release — the spec axis.
    out.push_str("## Release\n\n");
    let r = &status.release;
    let _ = writeln!(
        out,
        "- **SAS revision:** {}",
        r.version.as_deref().unwrap_or("*not recorded*")
    );
    if let Some(d) = &r.digest {
        let _ = writeln!(out, "- **digest:** `{d}`");
    }
    let _ = writeln!(out, "- {}", r.note);
    let c = &r.requirements;
    let _ = writeln!(
        out,
        "\n**Requirements ({} in §106)** — strictest rung first:\n",
        c.total()
    );
    let _ = writeln!(
        out,
        "| satisfied | in_progress | claimed | unaddressed | superseded |"
    );
    let _ = writeln!(out, "|---|---|---|---|---|");
    let _ = writeln!(
        out,
        "| **{}** | {} | {} | {} | {} |\n",
        c.satisfied, c.in_progress, c.claimed, c.unaddressed, c.superseded
    );

    // Objectives — the roadmap axis.
    out.push_str("## Objectives (SAS §98 phases)\n\n");
    out.push_str("| Objective | Exit Warrant | Achieved | invalid | draft | ready | would_satisfy | resolved |\n");
    out.push_str("|---|---|---|---|---|---|---|---|\n");
    for o in &status.objectives {
        let name = match &o.roadmap_ref {
            Some(r) => format!("{}: {}", r.canonical(), o.title),
            None => format!("*{}*", o.title),
        };
        let achieved = match &o.achieved {
            Achieved::NotDerivable { why } => format!("not derivable — {why}"),
            Achieved::Blocked { by } => format!("blocked by {}", by.join(", ")),
            Achieved::ExitWarrantWouldSatisfy => {
                "exit Warrant would satisfy; not recorded".to_owned()
            }
            Achieved::Recorded => "recorded".to_owned(),
        };
        let l = &o.ladder;
        let _ = writeln!(
            out,
            "| {name} | {} | {achieved} | {} | {} | {} | {} | {} |",
            o.exit_warrant.as_deref().unwrap_or("—"),
            l.invalid,
            l.draft,
            l.ready_to_resolve,
            l.would_satisfy,
            l.resolved
        );
    }
    out.push('\n');
    for o in status
        .objectives
        .iter()
        .filter(|o| o.exit_criterion.is_some())
    {
        if let (Some(r), Some(e)) = (&o.roadmap_ref, &o.exit_criterion) {
            let _ = writeln!(out, "- **{}** exit: {e}", r.canonical());
        }
    }
    out.push('\n');

    // Next actionable.
    out.push_str("## Next actionable\n\n");
    if status.next_actionable.is_empty() {
        if let Some(n) = &status.nothing_actionable {
            let _ = writeln!(out, "Nothing is unblocked. {}", n.why);
            if !n.blocked_by.is_empty() {
                let _ = writeln!(out, "\nBlocked by: {}", n.blocked_by.join(", "));
            }
        } else {
            out.push_str("Nothing is unblocked, and the projection could not say why. That is a defect in the projection.\n");
        }
    } else {
        for s in &status.next_actionable {
            let _ = writeln!(
                out,
                "- `{}` / `{}` / `{}` ({}) — {}",
                s.warrant,
                s.milestone,
                s.stage,
                s.objective.canonical(),
                s.why
            );
        }
    }
    out.push('\n');

    // What blocks, by requirement name.
    let blockers = status.blockers_by_requirement();
    if !blockers.is_empty() {
        out.push_str("## What blocks resolution, by §56.1 requirement\n\n");
        out.push_str(
            "Warrants blocked on each requirement. Names, not a score: this says what to fix.\n\n",
        );
        let mut rows: Vec<(&String, &usize)> = blockers.iter().collect();
        rows.sort_by(|a, b| b.1.cmp(a.1).then(a.0.cmp(b.0)));
        out.push_str("| requirement | Warrants blocked |\n|---|---|\n");
        for (name, n) in rows {
            let _ = writeln!(out, "| {name} | {n} |");
        }
        out.push('\n');
    }

    // Requirements — unaddressed listed by id.
    out.push_str("## Requirements (SAS §106, §34.3)\n\n");
    let unaddressed: Vec<_> = status
        .requirements
        .iter()
        .filter(|r| r.status == openwarrant_core::RequirementStatus::Unaddressed)
        .collect();
    if unaddressed.is_empty() {
        out.push_str("Every §106 requirement is named by at least one Warrant.\n\n");
    } else {
        let _ = writeln!(
            out,
            "**Unaddressed ({})** — no Warrant names these. Several may be built; the gap is bookkeeping, and it is listed rather than hidden:\n",
            unaddressed.len()
        );
        for r in &unaddressed {
            let _ = writeln!(
                out,
                "- `{}` — {}",
                r.requirement,
                r.title.as_deref().unwrap_or("*title unavailable*")
            );
        }
        out.push('\n');
    }
    out.push_str("| requirement | status | would_satisfy | implementers |\n|---|---|---|---|\n");
    for r in &status.requirements {
        let who: Vec<String> = r
            .links
            .iter()
            .map(|l| format!("{} ({})", l.warrant, l.intended_contribution))
            .collect();
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} |",
            r.requirement,
            r.status,
            r.would_satisfy,
            if who.is_empty() {
                "—".to_owned()
            } else {
                who.join(", ")
            }
        );
    }
    out.push('\n');

    // Warrants.
    let l = status.warrant_ladder();
    let _ = writeln!(
        out,
        "## Warrants ({}) — invalid {} · draft {} · ready_to_resolve {} · would_satisfy {} · resolved **{}**\n",
        l.total(),
        l.invalid,
        l.draft,
        l.ready_to_resolve,
        l.would_satisfy,
        l.resolved
    );
    out.push_str("| Warrant | rung | §38.6 | blocking unknowns | milestones evidenced | first unmet |\n|---|---|---|---|---|---|\n");
    for w in &status.warrants {
        let title = w.title.as_deref().unwrap_or("");
        let rung = match &w.validity {
            Validity::Invalid { reason } => format!("invalid — {reason}"),
            Validity::Valid => rung_word(w.rung).to_owned(),
        };
        let outcome = match w.would_resolve_satisfied {
            Some(true) => "would satisfy",
            Some(false) => "NOT satisfied",
            None => "unknown",
        };
        let evidenced = w.milestones.as_ref().map_or("—".to_owned(), |ms| {
            let e = ms
                .iter()
                .filter(|m| matches!(m.reached, Reached::Evidenced { .. }))
                .count();
            format!("{e} of {}", ms.len())
        });
        let first_unmet = w.unmet.first().map_or("—", String::as_str);
        let _ = writeln!(
            out,
            "| `{}` {title} | {rung} | {outcome} | {} | {evidenced} | {first_unmet} |",
            w.alias,
            w.blocking_unknowns.len()
        );
    }
    out.push('\n');

    out.push_str("## Not reported here\n\n");
    out.push_str("- Any percentage. Every number above is a rung count or a histogram of names.\n");
    out.push_str("- Recorded state. Nothing journals §24 transitions yet (OW-WAR-0031); everything above is derived from the records' shape.\n");
    out.push_str("- Whether a §98 Exit sentence is *true*. It is printed; it is not evaluated.\n");
    out
}
