// SPDX-License-Identifier: Apache-2.0
//! Render the corpus projection (SAS §17.5 `status`, corpus form).
//!
//! Two outputs from one value: Markdown for a person, RFC 8785 canonical JSON
//! for an agent. The JSON is the contract — a viewer, a Huly sync, a herdr
//! pane all read it and write nothing back (§77.3: consumers take generated
//! schemas; they do not reimplement WAR semantics).
//!
//! # No ratio, anywhere in this file
//!
//! Every number below is a rung count with the strictest rung first, or a
//! histogram of NAMES. `resolution.rs` says why: "'11 of 13' tells a reader
//! nothing about whether to worry." A percentage would be that sentence with
//! the 13 hidden.

use std::fmt::Write as _;

use openwarrant_core::status::{Achieved, CorpusStatus, Reached, Validity, WarrantRung};

use crate::canonical::{CanonicalError, to_canonical_string};

/// The canonical JSON an agent reads.
pub fn canonical_json(status: &CorpusStatus) -> Result<String, CanonicalError> {
    to_canonical_string(status)
}

fn rung_word(r: WarrantRung) -> &'static str {
    match r {
        WarrantRung::Invalid => "invalid",
        WarrantRung::Draft => "draft",
        WarrantRung::ReadyToResolve => "ready_to_resolve",
        WarrantRung::WouldSatisfy => "would_satisfy",
        WarrantRung::Resolved => "resolved",
    }
}

/// The Markdown a person reads.
pub fn render_markdown(status: &CorpusStatus) -> String {
    let mut out = String::new();
    out.push_str(
        "<!--\nGENERATED BY OPENWARRANT. DO NOT EDIT.\nSource: every Warrant under the configured warrants path, its sidecar records, and SAS §106.\n-->\n\n",
    );
    out.push_str("# Corpus Status\n\n");
    let _ = writeln!(
        out,
        "*Provenance: **{}**. {}*\n",
        status.provenance, status.provenance_note
    );

    if !status.caveats.is_empty() {
        out.push_str("## Read this first\n\n");
        for c in &status.caveats {
            let _ = writeln!(out, "- {c}");
        }
        out.push('\n');
    }

    // Release — the spec axis.
    out.push_str("## Release\n\n");
    let r = &status.release;
    let _ = writeln!(
        out,
        "- **SAS revision:** {}",
        r.version.as_deref().unwrap_or("*not recorded*")
    );
    if let Some(d) = &r.digest {
        let _ = writeln!(out, "- **digest:** `{d}`");
    }
    let _ = writeln!(out, "- {}", r.note);
    let c = &r.requirements;
    let _ = writeln!(
        out,
        "\n**Requirements ({} in §106)** — strictest rung first:\n",
        c.total()
    );
    let _ = writeln!(
        out,
        "| satisfied | in_progress | claimed | unaddressed | superseded |"
    );
    let _ = writeln!(out, "|---|---|---|---|---|");
    let _ = writeln!(
        out,
        "| **{}** | {} | {} | {} | {} |\n",
        c.satisfied, c.in_progress, c.claimed, c.unaddressed, c.superseded
    );

    // Objectives — the roadmap axis.
    out.push_str("## Objectives (SAS §98 phases)\n\n");
    out.push_str("| Objective | Exit Warrant | Achieved | invalid | draft | ready | would_satisfy | resolved |\n");
    out.push_str("|---|---|---|---|---|---|---|---|\n");
    for o in &status.objectives {
        let name = match &o.roadmap_ref {
            Some(r) => format!("{}: {}", r.canonical(), o.title),
            None => format!("*{}*", o.title),
        };
        let achieved = match &o.achieved {
            Achieved::NotDerivable { why } => format!("not derivable — {why}"),
            Achieved::Blocked { by } => format!("blocked by {}", by.join(", ")),
            Achieved::ExitWarrantWouldSatisfy => {
                "exit Warrant would satisfy; not recorded".to_owned()
            }
            Achieved::Recorded => "recorded".to_owned(),
        };
        let l = &o.ladder;
        let _ = writeln!(
            out,
            "| {name} | {} | {achieved} | {} | {} | {} | {} | {} |",
            o.exit_warrant.as_deref().unwrap_or("—"),
            l.invalid,
            l.draft,
            l.ready_to_resolve,
            l.would_satisfy,
            l.resolved
        );
    }
    out.push('\n');
    for o in status
        .objectives
        .iter()
        .filter(|o| o.exit_criterion.is_some())
    {
        if let (Some(r), Some(e)) = (&o.roadmap_ref, &o.exit_criterion) {
            let _ = writeln!(out, "- **{}** exit: {e}", r.canonical());
        }
    }
    out.push('\n');

    // Next actionable.
    out.push_str("## Next actionable\n\n");
    if status.next_actionable.is_empty() {
        if let Some(n) = &status.nothing_actionable {
            let _ = writeln!(out, "Nothing is unblocked. {}", n.why);
            if !n.blocked_by.is_empty() {
                let _ = writeln!(out, "\nBlocked by: {}", n.blocked_by.join(", "));
            }
        } else {
            out.push_str("Nothing is unblocked, and the projection could not say why. That is a defect in the projection.\n");
        }
    } else {
        for s in &status.next_actionable {
            let _ = writeln!(
                out,
                "- `{}` / `{}` / `{}` ({}) — {}",
                s.warrant,
                s.milestone,
                s.stage,
                s.objective.canonical(),
                s.why
            );
        }
    }
    out.push('\n');

    // What blocks, by requirement name.
    let blockers = status.blockers_by_requirement();
    if !blockers.is_empty() {
        out.push_str("## What blocks resolution, by §56.1 requirement\n\n");
        out.push_str(
            "Warrants blocked on each requirement. Names, not a score: this says what to fix.\n\n",
        );
        let mut rows: Vec<(&String, &usize)> = blockers.iter().collect();
        rows.sort_by(|a, b| b.1.cmp(a.1).then(a.0.cmp(b.0)));
        out.push_str("| requirement | Warrants blocked |\n|---|---|\n");
        for (name, n) in rows {
            let _ = writeln!(out, "| {name} | {n} |");
        }
        out.push('\n');
    }

    // Requirements — unaddressed listed by id.
    out.push_str("## Requirements (SAS §106, §34.3)\n\n");
    let unaddressed: Vec<_> = status
        .requirements
        .iter()
        .filter(|r| r.status == openwarrant_core::RequirementStatus::Unaddressed)
        .collect();
    if unaddressed.is_empty() {
        out.push_str("Every §106 requirement is named by at least one Warrant.\n\n");
    } else {
        let _ = writeln!(
            out,
            "**Unaddressed ({})** — no Warrant names these. Several may be built; the gap is bookkeeping, and it is listed rather than hidden:\n",
            unaddressed.len()
        );
        for r in &unaddressed {
            let _ = writeln!(
                out,
                "- `{}` — {}",
                r.requirement,
                r.title.as_deref().unwrap_or("*title unavailable*")
            );
        }
        out.push('\n');
    }
    out.push_str("| requirement | status | would_satisfy | implementers |\n|---|---|---|---|\n");
    for r in &status.requirements {
        let who: Vec<String> = r
            .links
            .iter()
            .map(|l| format!("{} ({})", l.warrant, l.intended_contribution))
            .collect();
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} |",
            r.requirement,
            r.status,
            r.would_satisfy,
            if who.is_empty() {
                "—".to_owned()
            } else {
                who.join(", ")
            }
        );
    }
    out.push('\n');

    // Warrants.
    let l = status.warrant_ladder();
    let _ = writeln!(
        out,
        "## Warrants ({}) — invalid {} · draft {} · ready_to_resolve {} · would_satisfy {} · resolved **{}**\n",
        l.total(),
        l.invalid,
        l.draft,
        l.ready_to_resolve,
        l.would_satisfy,
        l.resolved
    );
    out.push_str("| Warrant | rung | §38.6 | blocking unknowns | milestones evidenced | first unmet |\n|---|---|---|---|---|---|\n");
    for w in &status.warrants {
        let title = w.title.as_deref().unwrap_or("");
        let rung = match &w.validity {
            Validity::Invalid { reason } => format!("invalid — {reason}"),
            Validity::Valid => rung_word(w.rung).to_owned(),
        };
        let outcome = match w.would_resolve_satisfied {
            Some(true) => "would satisfy",
            Some(false) => "NOT satisfied",
            None => "unknown",
        };
        let evidenced = w.milestones.as_ref().map_or("—".to_owned(), |ms| {
            let e = ms
                .iter()
                .filter(|m| matches!(m.reached, Reached::Evidenced { .. }))
                .count();
            format!("{e} of {}", ms.len())
        });
        let first_unmet = w.unmet.first().map_or("—", String::as_str);
        let _ = writeln!(
            out,
            "| `{}` {title} | {rung} | {outcome} | {} | {evidenced} | {first_unmet} |",
            w.alias,
            w.blocking_unknowns.len()
        );
    }
    out.push('\n');

    out.push_str("## Not reported here\n\n");
    out.push_str("- Any percentage. Every number above is a rung count or a histogram of names.\n");
    out.push_str("- Recorded state. Nothing journals §24 transitions yet (OW-WAR-0031); everything above is derived from the records' shape.\n");
    out.push_str("- Whether a §98 Exit sentence is *true*. It is printed; it is not evaluated.\n");
    out
}

/// The page a person opens.
///
/// # One file, no fetch, deterministic
///
/// The canonical JSON is inlined verbatim in a `<script type="application/json">`
/// element and rendered by an inline script; the bytes of this file are a
/// fixed template plus that JSON, so the page drift-checks exactly like the
/// JSON does. Nothing is fetched and nothing is loaded from a host: the page
/// opens from disk with the network off, and a page that reached for live
/// state would be a second surface that could disagree with the committed
/// projection.
///
/// `</` inside the JSON is written `<\/` — a legal JSON escape — so no string
/// in the data can close the element that holds it.
///
/// # The renderer computes nothing
///
/// It reads counts the projection already made and prints them. There is no
/// division in it, for the same reason there is none in the Markdown renderer.
pub fn render_html(status: &CorpusStatus, canonical_json: &str) -> String {
    render_platform(status, canonical_json, None, None)
}

/// The progress platform (slices D3/D4): the status page plus the timeline
/// and pending projections, inlined, rendered by `app.js` into hash-routed
/// views. `None` for a sibling projection renders the page without that
/// view's data, and the view says so.
pub fn render_platform(
    status: &CorpusStatus,
    canonical_json: &str,
    timeline_json: Option<&str>,
    pending_json: Option<&str>,
) -> String {
    let embedded = canonical_json.replace("</", "<\\/");
    let l = status.warrant_ladder();
    let c = &status.release.requirements;
    let mut out = String::with_capacity(embedded.len() + 16_000);

    out.push_str("<!--\nGENERATED BY OPENWARRANT. DO NOT EDIT.\nSource: CORPUS_STATUS.json, inlined below and rendered in the browser.\n-->\n");
    out.push_str("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>Corpus Status</title>\n");
    out.push_str(HTML_STYLE);
    out.push_str("</head>\n<body>\n");

    // The banner is rendered server-side too, so it is present even before
    // the script runs and even if it never does.
    let _ = writeln!(
        out,
        "<aside class=\"banner\" role=\"note\"><strong>Provenance: {}.</strong> {}</aside>",
        esc(&status.provenance.to_string()),
        esc(&status.provenance_note)
    );
    out.push_str("<main>\n<h1>Corpus Status</h1>\n");
    let _ = writeln!(
        out,
        "<p class=\"meta\">Built from <a href=\"CORPUS_STATUS.json\">CORPUS_STATUS.json</a>; the same projection as <a href=\"CORPUS_STATUS.md\">CORPUS_STATUS.md</a>.</p>"
    );
    // A no-script fallback carrying the two headline ladders, so the page says
    // the true thing with scripting off.
    let _ = writeln!(
        out,
        "<noscript><p class=\"ladder\">Requirements — satisfied <b>{}</b> · in_progress {} · claimed {} · unaddressed {} · superseded {}</p>\
         <p class=\"ladder\">Warrants — resolved <b>{}</b> · would_satisfy {} · ready_to_resolve {} · draft {} · invalid {}</p>\
         <p>Enable scripting for the full page, or read CORPUS_STATUS.md.</p></noscript>",
        c.satisfied,
        c.in_progress,
        c.claimed,
        c.unaddressed,
        c.superseded,
        l.resolved,
        l.would_satisfy,
        l.ready_to_resolve,
        l.draft,
        l.invalid
    );
    out.push_str("<div id=\"app\"></div>\n</main>\n");
    let _ = writeln!(
        out,
        "<script id=\"corpus-status\" type=\"application/json\">{embedded}</script>"
    );
    for (id, blob) in [
        ("corpus-timeline", timeline_json),
        ("corpus-pending", pending_json),
    ] {
        if let Some(json) = blob {
            let _ = writeln!(
                out,
                "<script id=\"{id}\" type=\"application/json\">{}</script>",
                json.replace("</", "<\\/")
            );
        }
    }
    out.push_str(HTML_SCRIPT);
    out.push_str("</body>\n</html>\n");
    out
}

/// Text-and-attribute-safe HTML escaping. The single quote is included even
/// though no call site puts data in a single-quoted attribute today: an
/// escaper that is safe only in the contexts its author remembered is the
/// kind that gets reused in the one it did not.
fn esc(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

/// The stylesheet and the app, kept as files beside this module so they are
/// edited as CSS and JavaScript and included byte-for-byte: no build step, no
/// package manager, no second licence gate. The app reaches for nothing —
/// a plant greps the rendered page for `fetch(`, `<script src=`, `<link `
/// and `url(`.
const HTML_STYLE: &str = concat!(
    "<style>\n",
    include_str!("corpus_status/app.css"),
    "</style>\n"
);

const HTML_SCRIPT: &str = concat!(
    "<script>\n",
    include_str!("corpus_status/app.js"),
    "</script>\n"
);

#[cfg(test)]
mod tests {
    use super::*;

    /// OW-WAR-0057 OBL-002 — the provenance banner precedes the title, and the
    /// renderer computes no ratio: its source has no division. Rendered from
    /// the committed projection so no fixture has to be hand-built.
    #[test]
    fn the_banner_precedes_the_title_and_the_renderer_divides_nothing() {
        let src = include_str!("corpus_status.rs");
        let body = src.split("#[cfg(test)]").next().unwrap_or(src);
        // A division OPERATOR: `/` between two code tokens, on a line that is
        // neither a comment nor a string literal (" / " inside a quoted label
        // is text, not arithmetic).
        let app = include_str!("corpus_status/app.js");
        let divides = body.lines().chain(app.lines()).any(|l| {
            let t = l.trim_start();
            !t.starts_with("//") && !t.contains('"') && !t.contains('\'') && t.contains(" / ")
        });
        assert!(!divides, "a ratio crept into the renderer or the app");
        // The app builds the DOM through textContent and text nodes only, and
        // fetches nothing.
        assert!(!app.contains("innerHTML"), "innerHTML in the app");
        assert!(!app.contains("fetch("), "the app fetches");
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../docs/warrants/generated/CORPUS_STATUS.json"),
        )
        .expect("committed projection");
        let status: openwarrant_core::status::CorpusStatus =
            serde_json::from_str(&json).expect("parses");
        let html = render_html(&status, &json);
        let banner = html.find("class=\"banner\"").expect("banner");
        let title = html.find("<h1>").expect("title");
        assert!(banner < title, "banner must precede the title");
    }

    /// OW-WAR-0058 OBL-005 — every committed WAR.json carries the SAS pin.
    #[test]
    fn every_committed_war_json_carries_the_sas_pin() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/warrants");
        let mut n = 0;
        for entry in std::fs::read_dir(&root).expect("warrants") {
            let p = entry.expect("entry").path().join("generated/WAR.json");
            if !p.is_file() {
                continue;
            }
            let v: serde_json::Value =
                serde_json::from_str(&std::fs::read_to_string(&p).expect("read")).expect("json");
            let fb = &v["format_basis"];
            assert!(
                fb["sas_revision"].is_string() && fb["sas_digest"].is_string(),
                "{} lacks the SAS pin",
                p.display()
            );
            n += 1;
        }
        assert!(n >= 50, "only {n} WAR.json files found");
    }
}
