// SPDX-License-Identifier: AGPL-3.0-or-later
//! Render the corpus projection (SAS §17.5 `status`, corpus form).
//!
//! Two outputs from one value: Markdown for a person, RFC 8785 canonical JSON
//! for an agent. The JSON is the contract — a viewer, a Huly sync, a herdr
//! pane all read it and write nothing back (§77.3: consumers take generated
//! schemas; they do not reimplement WAR semantics).
//!
//! # No ratio, anywhere in this file
//!
//! Every number below is a rung count with the strictest rung first, or a
//! histogram of NAMES. `resolution.rs` says why: "'11 of 13' tells a reader
//! nothing about whether to worry." A percentage would be that sentence with
//! the 13 hidden.

use std::fmt::Write as _;

use openwarrant_core::status::{Achieved, CorpusStatus, Reached, Validity, WarrantRung};

use crate::canonical::{CanonicalError, to_canonical_string};

/// The canonical JSON an agent reads.
pub fn canonical_json(status: &CorpusStatus) -> Result<String, CanonicalError> {
    to_canonical_string(status)
}

fn rung_word(r: WarrantRung) -> &'static str {
    match r {
        WarrantRung::Invalid => "invalid",
        WarrantRung::Draft => "draft",
        WarrantRung::ReadyToResolve => "ready_to_resolve",
        WarrantRung::WouldSatisfy => "would_satisfy",
        WarrantRung::Resolved => "resolved",
    }
}

/// The Markdown a person reads.
pub fn render_markdown(status: &CorpusStatus) -> String {
    let mut out = String::new();
    out.push_str(
        "<!--\nGENERATED BY OPENWARRANT. DO NOT EDIT.\nSource: every Warrant under the configured warrants path, its sidecar records, and SAS §106.\n-->\n\n",
    );
    out.push_str("# Corpus Status\n\n");
    let _ = writeln!(
        out,
        "*Provenance: **{}**. {}*\n",
        status.provenance, status.provenance_note
    );

    if !status.caveats.is_empty() {
        out.push_str("## Read this first\n\n");
        for c in &status.caveats {
            let _ = writeln!(out, "- {c}");
        }
        out.push('\n');
    }

    // Release — the spec axis.
    out.push_str("## Release\n\n");
    let r = &status.release;
    let _ = writeln!(
        out,
        "- **SAS revision:** {}",
        r.version.as_deref().unwrap_or("*not recorded*")
    );
    if let Some(d) = &r.digest {
        let _ = writeln!(out, "- **digest:** `{d}`");
    }
    let _ = writeln!(out, "- {}", r.note);
    let c = &r.requirements;
    let _ = writeln!(
        out,
        "\n**Requirements ({} in §106)** — strictest rung first:\n",
        c.total()
    );
    let _ = writeln!(
        out,
        "| satisfied | in_progress | claimed | unaddressed | superseded |"
    );
    let _ = writeln!(out, "|---|---|---|---|---|");
    let _ = writeln!(
        out,
        "| **{}** | {} | {} | {} | {} |\n",
        c.satisfied, c.in_progress, c.claimed, c.unaddressed, c.superseded
    );

    // Objectives — the roadmap axis.
    out.push_str("## Objectives (SAS §98 phases)\n\n");
    out.push_str("| Objective | Exit Warrant | Achieved | invalid | draft | ready | would_satisfy | resolved |\n");
    out.push_str("|---|---|---|---|---|---|---|---|\n");
    for o in &status.objectives {
        let name = match &o.roadmap_ref {
            Some(r) => format!("{}: {}", r.canonical(), o.title),
            None => format!("*{}*", o.title),
        };
        let achieved = match &o.achieved {
            Achieved::NotDerivable { why } => format!("not derivable — {why}"),
            Achieved::Blocked { by } => format!("blocked by {}", by.join(", ")),
            Achieved::ExitWarrantWouldSatisfy => {
                "exit Warrant would satisfy; not recorded".to_owned()
            }
            Achieved::Recorded => "recorded".to_owned(),
        };
        let l = &o.ladder;
        let _ = writeln!(
            out,
            "| {name} | {} | {achieved} | {} | {} | {} | {} | {} |",
            o.exit_warrant.as_deref().unwrap_or("—"),
            l.invalid,
            l.draft,
            l.ready_to_resolve,
            l.would_satisfy,
            l.resolved
        );
    }
    out.push('\n');
    for o in status
        .objectives
        .iter()
        .filter(|o| o.exit_criterion.is_some())
    {
        if let (Some(r), Some(e)) = (&o.roadmap_ref, &o.exit_criterion) {
            let _ = writeln!(out, "- **{}** exit: {e}", r.canonical());
        }
    }
    out.push('\n');

    // Next actionable.
    out.push_str("## Next actionable\n\n");
    if status.next_actionable.is_empty() {
        if let Some(n) = &status.nothing_actionable {
            let _ = writeln!(out, "Nothing is unblocked. {}", n.why);
            if !n.blocked_by.is_empty() {
                let _ = writeln!(out, "\nBlocked by: {}", n.blocked_by.join(", "));
            }
        } else {
            out.push_str("Nothing is unblocked, and the projection could not say why. That is a defect in the projection.\n");
        }
    } else {
        for s in &status.next_actionable {
            let _ = writeln!(
                out,
                "- `{}` / `{}` / `{}` ({}) — {}",
                s.warrant,
                s.milestone,
                s.stage,
                s.objective.canonical(),
                s.why
            );
        }
    }
    out.push('\n');

    // What blocks, by requirement name.
    let blockers = status.blockers_by_requirement();
    if !blockers.is_empty() {
        out.push_str("## What blocks resolution, by §56.1 requirement\n\n");
        out.push_str(
            "Warrants blocked on each requirement. Names, not a score: this says what to fix.\n\n",
        );
        let mut rows: Vec<(&String, &usize)> = blockers.iter().collect();
        rows.sort_by(|a, b| b.1.cmp(a.1).then(a.0.cmp(b.0)));
        out.push_str("| requirement | Warrants blocked |\n|---|---|\n");
        for (name, n) in rows {
            let _ = writeln!(out, "| {name} | {n} |");
        }
        out.push('\n');
    }

    // Requirements — unaddressed listed by id.
    out.push_str("## Requirements (SAS §106, §34.3)\n\n");
    let unaddressed: Vec<_> = status
        .requirements
        .iter()
        .filter(|r| r.status == openwarrant_core::RequirementStatus::Unaddressed)
        .collect();
    if unaddressed.is_empty() {
        out.push_str("Every §106 requirement is named by at least one Warrant.\n\n");
    } else {
        let _ = writeln!(
            out,
            "**Unaddressed ({})** — no Warrant names these. Several may be built; the gap is bookkeeping, and it is listed rather than hidden:\n",
            unaddressed.len()
        );
        for r in &unaddressed {
            let _ = writeln!(
                out,
                "- `{}` — {}",
                r.requirement,
                r.title.as_deref().unwrap_or("*title unavailable*")
            );
        }
        out.push('\n');
    }
    out.push_str("| requirement | status | would_satisfy | implementers |\n|---|---|---|---|\n");
    for r in &status.requirements {
        let who: Vec<String> = r
            .links
            .iter()
            .map(|l| format!("{} ({})", l.warrant, l.intended_contribution))
            .collect();
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} |",
            r.requirement,
            r.status,
            r.would_satisfy,
            if who.is_empty() {
                "—".to_owned()
            } else {
                who.join(", ")
            }
        );
    }
    out.push('\n');

    // Warrants.
    let l = status.warrant_ladder();
    let _ = writeln!(
        out,
        "## Warrants ({}) — invalid {} · draft {} · ready_to_resolve {} · would_satisfy {} · resolved **{}**\n",
        l.total(),
        l.invalid,
        l.draft,
        l.ready_to_resolve,
        l.would_satisfy,
        l.resolved
    );
    out.push_str("| Warrant | rung | §38.6 | blocking unknowns | milestones evidenced | first unmet |\n|---|---|---|---|---|---|\n");
    for w in &status.warrants {
        let title = w.title.as_deref().unwrap_or("");
        let rung = match &w.validity {
            Validity::Invalid { reason } => format!("invalid — {reason}"),
            Validity::Valid => rung_word(w.rung).to_owned(),
        };
        let outcome = match w.would_resolve_satisfied {
            Some(true) => "would satisfy",
            Some(false) => "NOT satisfied",
            None => "unknown",
        };
        let evidenced = w.milestones.as_ref().map_or("—".to_owned(), |ms| {
            let e = ms
                .iter()
                .filter(|m| matches!(m.reached, Reached::Evidenced { .. }))
                .count();
            format!("{e} of {}", ms.len())
        });
        let first_unmet = w.unmet.first().map_or("—", String::as_str);
        let _ = writeln!(
            out,
            "| `{}` {title} | {rung} | {outcome} | {} | {evidenced} | {first_unmet} |",
            w.alias,
            w.blocking_unknowns.len()
        );
    }
    out.push('\n');

    out.push_str("## Not reported here\n\n");
    out.push_str("- Any percentage. Every number above is a rung count or a histogram of names.\n");
    out.push_str("- Recorded state. Nothing journals §24 transitions yet (OW-WAR-0031); everything above is derived from the records' shape.\n");
    out.push_str("- Whether a §98 Exit sentence is *true*. It is printed; it is not evaluated.\n");
    out
}

/// The page a person opens.
///
/// # One file, no fetch, deterministic
///
/// The canonical JSON is inlined verbatim in a `<script type="application/json">`
/// element and rendered by an inline script; the bytes of this file are a
/// fixed template plus that JSON, so the page drift-checks exactly like the
/// JSON does. Nothing is fetched and nothing is loaded from a host: the page
/// opens from disk with the network off, and a page that reached for live
/// state would be a second surface that could disagree with the committed
/// projection.
///
/// `</` inside the JSON is written `<\/` — a legal JSON escape — so no string
/// in the data can close the element that holds it.
///
/// # The renderer computes nothing
///
/// It reads counts the projection already made and prints them. There is no
/// division in it, for the same reason there is none in the Markdown renderer.
pub fn render_html(status: &CorpusStatus, canonical_json: &str) -> String {
    let embedded = canonical_json.replace("</", "<\\/");
    let l = status.warrant_ladder();
    let c = &status.release.requirements;
    let mut out = String::with_capacity(embedded.len() + 16_000);

    out.push_str("<!--\nGENERATED BY OPENWARRANT. DO NOT EDIT.\nSource: CORPUS_STATUS.json, inlined below and rendered in the browser.\n-->\n");
    out.push_str("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>Corpus Status</title>\n");
    out.push_str(HTML_STYLE);
    out.push_str("</head>\n<body>\n");

    // The banner is rendered server-side too, so it is present even before
    // the script runs and even if it never does.
    let _ = writeln!(
        out,
        "<aside class=\"banner\" role=\"note\"><strong>Provenance: {}.</strong> {}</aside>",
        esc(&status.provenance.to_string()),
        esc(&status.provenance_note)
    );
    out.push_str("<main>\n<h1>Corpus Status</h1>\n");
    let _ = writeln!(
        out,
        "<p class=\"meta\">Built from <a href=\"CORPUS_STATUS.json\">CORPUS_STATUS.json</a>; the same projection as <a href=\"CORPUS_STATUS.md\">CORPUS_STATUS.md</a>.</p>"
    );
    // A no-script fallback carrying the two headline ladders, so the page says
    // the true thing with scripting off.
    let _ = writeln!(
        out,
        "<noscript><p class=\"ladder\">Requirements — satisfied <b>{}</b> · in_progress {} · claimed {} · unaddressed {} · superseded {}</p>\
         <p class=\"ladder\">Warrants — resolved <b>{}</b> · would_satisfy {} · ready_to_resolve {} · draft {} · invalid {}</p>\
         <p>Enable scripting for the full page, or read CORPUS_STATUS.md.</p></noscript>",
        c.satisfied,
        c.in_progress,
        c.claimed,
        c.unaddressed,
        c.superseded,
        l.resolved,
        l.would_satisfy,
        l.ready_to_resolve,
        l.draft,
        l.invalid
    );
    out.push_str("<div id=\"app\"></div>\n</main>\n");
    let _ = writeln!(
        out,
        "<script id=\"corpus-status\" type=\"application/json\">{embedded}</script>"
    );
    out.push_str(HTML_SCRIPT);
    out.push_str("</body>\n</html>\n");
    out
}

/// Text-and-attribute-safe HTML escaping. The single quote is included even
/// though no call site puts data in a single-quoted attribute today: an
/// escaper that is safe only in the contexts its author remembered is the
/// kind that gets reused in the one it did not.
fn esc(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

const HTML_STYLE: &str = r#"<style>
:root{color-scheme:light dark;--bg:#fafaf9;--fg:#1c1917;--muted:#57534e;--line:#e7e5e4;--card:#ffffff;--accent:#0f766e;--warn:#b45309;--bad:#b91c1c;--ok:#15803d}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){--bg:#0c0a09;--fg:#e7e5e4;--muted:#a8a29e;--line:#292524;--card:#1c1917;--accent:#2dd4bf;--warn:#f59e0b;--bad:#f87171;--ok:#4ade80}}
:root[data-theme="dark"]{--bg:#0c0a09;--fg:#e7e5e4;--muted:#a8a29e;--line:#292524;--card:#1c1917;--accent:#2dd4bf;--warn:#f59e0b;--bad:#f87171;--ok:#4ade80}
body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.5 ui-sans-serif,system-ui,sans-serif}
main{max-width:1100px;margin:0 auto;padding:1rem 1.25rem 4rem}
.banner{background:var(--card);border-left:4px solid var(--warn);padding:.75rem 1rem;margin:0;font-size:.95rem}
h1{font-size:1.6rem;margin:1.25rem 0 .25rem}h2{font-size:1.15rem;margin:2rem 0 .5rem;border-bottom:1px solid var(--line);padding-bottom:.25rem}
.meta,.muted{color:var(--muted)}.ladder{font-variant-numeric:tabular-nums}
.caveats{background:var(--card);border:1px solid var(--line);border-radius:6px;padding:.5rem 1rem;margin:1rem 0}.caveats li{margin:.25rem 0}
.rungs{display:flex;flex-wrap:wrap;gap:.5rem;margin:.5rem 0}.rung{background:var(--card);border:1px solid var(--line);border-radius:6px;padding:.4rem .7rem;font-variant-numeric:tabular-nums}.rung b{font-size:1.25rem;display:block}.rung.head{border-color:var(--accent)}
.scroll{overflow-x:auto}table{border-collapse:collapse;width:100%;font-size:.9rem}th,td{text-align:left;padding:.35rem .5rem;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--muted);font-weight:600}code{font:.85em ui-monospace,monospace}
.pill{display:inline-block;border-radius:999px;padding:0 .5rem;font-size:.8rem;border:1px solid var(--line)}.pill.ok{color:var(--ok)}.pill.warn{color:var(--warn)}.pill.bad{color:var(--bad)}
ul.next li{margin:.3rem 0}footer{margin-top:3rem;color:var(--muted);font-size:.9rem}
</style>
"#;

const HTML_SCRIPT: &str = r#"<script>
(function(){
  var el=document.getElementById('corpus-status'); if(!el) return;
  var d=JSON.parse(el.textContent); var app=document.getElementById('app');
  // No innerHTML path, on purpose: every string from the JSON reaches the DOM through textContent or a text node.
  function h(tag,attrs,kids){var e=document.createElement(tag); if(attrs) for(var k in attrs){ if(k==='text') e.textContent=attrs[k]; else e.setAttribute(k,attrs[k]); } (kids||[]).forEach(function(c){ if(c==null) return; e.appendChild(typeof c==='string'?document.createTextNode(c):c); }); return e;}
  function rung(label,n,head){return h('div',{class:'rung'+(head?' head':'')},[h('b',{text:String(n)}),document.createTextNode(label)]);}
  function count(list,key,val){var n=0; list.forEach(function(x){ if(x[key]===val) n++; }); return n;}
  function ref(r){return r? (r.slug? 'roadmap://'+r.prefix+'-PHASE-'+r.phase+'/'+r.slug : 'roadmap://'+r.prefix+'-PHASE-'+r.phase) : '';}
  function rq(r){return r.prefix+'-SAS-RQ-'+String(r.number).padStart(3,'0');}
  function table(head,rows){var t=h('table'); var tr=h('tr'); head.forEach(function(x){tr.appendChild(h('th',{text:x}));}); t.appendChild(h('thead',null,[tr])); var tb=h('tbody'); rows.forEach(function(r){var tr2=h('tr'); r.forEach(function(c){tr2.appendChild(h('td',null,[c]));}); tb.appendChild(tr2);}); t.appendChild(tb); return h('div',{class:'scroll'},[t]);}

  if(d.caveats && d.caveats.length){ app.appendChild(h('h2',{text:'Read this first'})); app.appendChild(h('ul',{class:'caveats'}, d.caveats.map(function(c){return h('li',{text:c});}))); }

  app.appendChild(h('h2',{text:'Release'}));
  var rel=d.release; app.appendChild(h('p',{class:'muted',text:'SAS revision: '+(rel.version||'not recorded')+'. '+rel.note}));
  var c=rel.requirements; app.appendChild(h('p',{text:'Requirements — '+(c.satisfied+c.in_progress+c.claimed+c.unaddressed+c.superseded)+' in §106, strictest rung first:'}));
  app.appendChild(h('div',{class:'rungs'},[rung('satisfied',c.satisfied,true),rung('in_progress',c.in_progress),rung('claimed',c.claimed),rung('unaddressed',c.unaddressed),rung('superseded',c.superseded)]));

  app.appendChild(h('h2',{text:'Objectives (SAS §98 phases)'}));
  app.appendChild(table(['Objective','Exit Warrant','Achieved','invalid','draft','ready','would_satisfy','resolved'], d.objectives.map(function(o){
    var a=o.achieved, at=a.state==='not_derivable'?'not derivable — '+a.why : a.state==='blocked'?'blocked by '+a.by.join(', ') : a.state==='exit_warrant_would_satisfy'?'exit Warrant would satisfy; not recorded':'recorded';
    var name=o.roadmap_ref? ref(o.roadmap_ref)+': '+o.title : o.title; var l=o.ladder;
    return [h('span',{text:name}),h('code',{text:o.exit_warrant||'—'}),h('span',{text:at}),String(l.invalid),String(l.draft),String(l.ready_to_resolve),String(l.would_satisfy),String(l.resolved)];
  })));
  app.appendChild(h('ul',{class:'muted'}, d.objectives.filter(function(o){return o.exit_criterion;}).map(function(o){return h('li',null,[h('b',{text:ref(o.roadmap_ref)}),' exit: '+o.exit_criterion]);})));

  app.appendChild(h('h2',{text:'Next actionable'}));
  if(d.next_actionable.length){ app.appendChild(h('ul',{class:'next'}, d.next_actionable.map(function(s){return h('li',null,[h('code',{text:s.warrant+' / '+s.milestone+' / '+s.stage}),' ('+ref(s.objective)+') — '+s.why]);}))); }
  else { var n=d.nothing_actionable; app.appendChild(h('p',{text: n? ('Nothing is unblocked. '+n.why+(n.blocked_by.length?' Blocked by: '+n.blocked_by.join(', '):'')) : 'Nothing is unblocked, and the projection could not say why. That is a defect in the projection.'})); }

  var blockers={}; d.warrants.forEach(function(w){ w.unmet.forEach(function(u){ blockers[u]=(blockers[u]||0)+1; }); });
  var bk=Object.keys(blockers).sort(function(a,b){return blockers[b]-blockers[a]||a.localeCompare(b);});
  if(bk.length){ app.appendChild(h('h2',{text:'What blocks resolution, by §56.1 requirement'})); app.appendChild(h('p',{class:'muted',text:'Warrants blocked on each requirement. Names, not a score: this says what to fix.'})); app.appendChild(table(['requirement','Warrants blocked'], bk.map(function(k){return [k,String(blockers[k])];}))); }

  app.appendChild(h('h2',{text:'Requirements (SAS §106, §34.3)'}));
  var un=d.requirements.filter(function(r){return r.status==='unaddressed';});
  if(un.length){ app.appendChild(h('p',null,[h('b',{text:'Unaddressed ('+un.length+')'}),' — no Warrant names these. Several may be built; the gap is bookkeeping, and it is listed rather than hidden:'])); app.appendChild(h('ul',null,un.map(function(r){return h('li',null,[h('code',{text:rq(r.requirement)}),' — '+(r.title||'title unavailable')]);}))); }
  app.appendChild(table(['requirement','status','would_satisfy','implementers'], d.requirements.map(function(r){ var who=r.links.map(function(l){return l.warrant+' ('+l.intended_contribution+')';}).join(', ')||'—'; return [h('code',{text:rq(r.requirement)}),r.status,String(r.would_satisfy),who]; })));

  var L={invalid:count(d.warrants,'rung','invalid'),draft:count(d.warrants,'rung','draft'),ready:count(d.warrants,'rung','ready_to_resolve'),ws:count(d.warrants,'rung','would_satisfy'),res:count(d.warrants,'rung','resolved')};
  app.appendChild(h('h2',{text:'Warrants ('+d.warrants.length+')'}));
  app.appendChild(h('div',{class:'rungs'},[rung('resolved',L.res,true),rung('would_satisfy',L.ws),rung('ready_to_resolve',L.ready),rung('draft',L.draft),rung('invalid',L.invalid)]));
  app.appendChild(table(['Warrant','rung','§38.6','blocking unknowns','milestones evidenced','first unmet'], d.warrants.map(function(w){
    var rungTxt = w.validity.state==='invalid' ? 'invalid — '+w.validity.reason : w.rung;
    var o = w.would_resolve_satisfied===true?'would satisfy': w.would_resolve_satisfied===false?'NOT satisfied':'unknown';
    var ev = w.milestones? (count(w.milestones.map(function(m){return m.reached;}),'state','evidenced')+' of '+w.milestones.length) : '—';
    return [h('span',null,[h('code',{text:w.alias}),' '+(w.title||'')]), rungTxt, h('span',{class:'pill '+(o==='would satisfy'?'ok':o==='unknown'?'warn':'bad'),text:o}), String(w.blocking_unknowns.length), ev, (w.unmet[0]||'—')];
  })));

  var f=h('footer',null,[h('h2',{text:'Not reported here'}),h('ul',null,[
    h('li',{text:'Any percentage. Every number above is a rung count or a histogram of names.'}),
    h('li',{text:'Recorded state. Nothing journals §24 transitions yet (OW-WAR-0031); everything above is derived from the records\' shape.'}),
    h('li',{text:'Whether a §98 Exit sentence is true. It is printed; it is not evaluated.'})])]);
  app.appendChild(f);
})();
</script>
"#;
