// SPDX-License-Identifier: Apache-2.0
//! The history, `docs/generated/HISTORY.md` (OW-ADR-0022, RQ-084).
//!
//! Optional — written when `[generated] history = true`. Where the master
//! document holds what IS, this holds what WAS as well: every subject that
//! ever existed, the lineage chains that replaced them, every subject's atoms
//! expanded (superseded ones included), the recorded timeline, and every ADR
//! with its status. It is the audit trail §21.4 and RQ-084 promise, kept out
//! of the master document so the master document can stay current.
//!
//! Rendered from the same [`Corpus`] as the master document: one gathering,
//! two renderings, so the two cannot disagree about what a subject is.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::current::{Corpus, Subject, link, subject};

/// Render the history.
#[must_use]
pub fn render(c: &Corpus) -> String {
    let mut out = String::new();
    let _ = write!(
        out,
        "<!--\nGENERATED BY OPENWARRANT (`war compile`). DO NOT EDIT.\nSource: the atoms and records of this repository. `war check --generated` refuses a hand edit.\n-->\n\n\
         # {program} — the history\n\n\
         Everything this repository has recorded, current or not: {n} subject(s), \
         their lineage, every atom expanded, the timeline and every decision with its \
         status. What is authoritative now is in the master document; this is what it \
         replaced and how. Records as of {date}.\n\n",
        program = c.program,
        n = c.subjects.len(),
        date = c.tree_date.as_deref().unwrap_or("no recorded event"),
    );
    lineage(c, &mut out);
    timeline(c, &mut out);
    roadmap_revisions(c, &mut out);
    decisions(c, &mut out);
    subjects(c, &mut out);
    out
}

/// Chains of supersession, oldest first: `A → B → C`. A chain starts at a
/// subject nothing it replaced precedes, and follows `replaced_by`.
fn lineage(c: &Corpus, out: &mut String) {
    out.push_str("## Lineage\n\n");
    let by: BTreeMap<&str, &Subject> = c.subjects.iter().map(|s| (s.alias.as_str(), s)).collect();
    let successors_of = |s: &Subject| -> Vec<String> {
        s.replaced_by
            .as_deref()
            .map(|b| b.split(", ").map(str::to_owned).collect())
            .unwrap_or_default()
    };
    let replaced_targets: std::collections::BTreeSet<String> =
        c.subjects.iter().flat_map(successors_of).collect();
    let mut chains = Vec::new();
    for s in &c.subjects {
        if s.is_current() && s.replaced_by.is_none() && !replaced_targets.contains(&s.alias) {
            continue;
        }
        if replaced_targets.contains(&s.alias) {
            continue; // not a chain's start
        }
        let mut chain = vec![s.alias.clone()];
        let mut at: &Subject = s;
        let mut seen = std::collections::BTreeSet::new();
        loop {
            let next = successors_of(at);
            if next.is_empty() {
                if !at.is_current() && at.replaced_by.is_none() {
                    chain.push(at.currency.clone());
                }
                break;
            }
            chain.push(next.join(" + "));
            let Some(n) = next.first().and_then(|a| by.get(a.as_str())) else {
                break;
            };
            if !seen.insert(n.alias.clone()) {
                break;
            }
            at = *n;
        }
        chains.push(chain.join(" → "));
    }
    if chains.is_empty() {
        out.push_str("No subject has been replaced.\n\n");
    } else {
        for chain in chains {
            let _ = writeln!(out, "- {chain}");
        }
        out.push('\n');
    }
}

fn timeline(c: &Corpus, out: &mut String) {
    out.push_str("## Timeline\n\n");
    if c.timeline.is_empty() {
        out.push_str("No event is recorded.\n\n");
        return;
    }
    out.push_str("| date | events | by type |\n|---|---|---|\n");
    for d in &c.timeline {
        let _ = writeln!(
            out,
            "| {} | {} | {} |",
            d.date,
            d.events,
            d.by_type
                .iter()
                .map(|(t, n)| format!("{t} {n}"))
                .collect::<Vec<_>>()
                .join(", ")
        );
    }
    out.push('\n');
}

/// Every revision of the roadmap record, oldest first, each with the phases
/// it recorded and its diff against its predecessor; and the plans the record
/// retired. The master document shows only the revision in force
/// (OW-ADR-0023 decision 6).
fn roadmap_revisions(c: &Corpus, out: &mut String) {
    out.push_str("## Roadmap revisions\n\n");
    let Some(r) = &c.roadmap else {
        out.push_str("No roadmap record.\n\n");
        return;
    };
    if r.revisions.is_empty() {
        out.push_str("The roadmap record has no revision on record.\n\n");
    }
    for v in &r.revisions {
        let _ = writeln!(
            out,
            "### Revision {} — {}\n\n[record]({}) · sha256:`{}` · predecessor {}{}\n",
            v.revision,
            v.state,
            link(&v.record),
            v.sha256,
            v.predecessor
                .map_or_else(|| "none".to_owned(), |n| format!("revision {n}")),
            match (&v.accepted_by, &v.effective_time) {
                (Some(by), Some(at)) => format!(" · accepted by {by} at {at}"),
                (Some(by), None) => format!(" · accepted by {by}"),
                _ => String::new(),
            }
        );
        let _ = writeln!(out, "- **Diff against its predecessor:** {}", v.diff);
        if let Some(note) = &v.note {
            let _ = writeln!(out, "- **Proposer's note:** {note}");
        }
        let _ = writeln!(
            out,
            "- **Phases ({}):** {}\n",
            v.phases.len(),
            v.phases
                .iter()
                .map(|(id, t)| format!("{id} {t}"))
                .collect::<Vec<_>>()
                .join("; ")
        );
    }
    if !r.retires.is_empty() {
        out.push_str("### Plans the record retired\n\n");
        for t in &r.retires {
            let _ = writeln!(out, "- `{}` → {}", t.path, t.lineage);
        }
        out.push('\n');
    }
}

fn decisions(c: &Corpus, out: &mut String) {
    out.push_str("## Decisions\n\n");
    if c.decisions.is_empty() {
        out.push_str("No decision is recorded.\n\n");
        return;
    }
    for d in &c.decisions {
        let _ = writeln!(
            out,
            "### {} — {} (`{}`)\n\n[source]({})\n\n{}\n",
            d.alias,
            d.title,
            d.status,
            link(&d.source),
            d.body.trim_end()
        );
    }
}

fn subjects(c: &Corpus, out: &mut String) {
    out.push_str("## Subjects\n\n");
    let mut all: Vec<&Subject> = c.subjects.iter().collect();
    all.sort_by(|a, b| a.alias.cmp(&b.alias));
    for s in all {
        if let Some(by) = &s.replaced_by {
            let _ = writeln!(out, "> {} was replaced by {by}.\n", s.alias);
        }
        subject(s, 3, out);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::current::Atom;

    fn s(alias: &str, currency: &str, by: Option<&str>) -> Subject {
        Subject {
            alias: alias.into(),
            title: "t".into(),
            manifest: "m".into(),
            profile: "delivery".into(),
            currency: currency.into(),
            replaced_by: by.map(Into::into),
            phase: None,
            rung: "draft".into(),
            basis_revision: None,
            contract_revision: None,
            contract_digest: None,
            authorization: None,
            resolution: None,
            atoms: vec![Atom {
                ordinal: 10,
                role: "intent".into(),
                source: format!("{alias}/10-intent.md"),
                body: format!("{alias} INTENT\n"),
                structured: false,
            }],
            deliverables: vec![],
        }
    }

    #[test]
    fn the_history_carries_every_roadmap_revision() {
        use crate::current::{Roadmap, RoadmapRevisionEntry};
        let rev = |n: u32, state: &str, diff: &str| RoadmapRevisionEntry {
            revision: n,
            state: state.into(),
            record: format!("docs/roadmap/revisions/{n}.toml"),
            predecessor: n.checked_sub(1).filter(|p| *p > 0),
            diff: diff.into(),
            phases: vec![("P-PHASE-0".into(), "Start".into())],
            ..RoadmapRevisionEntry::default()
        };
        let c = Corpus {
            roadmap: Some(Roadmap {
                revisions: vec![
                    rev(1, "accepted", "+1"),
                    rev(2, "accepted", "P-PHASE-0 +open x"),
                ],
                ..Roadmap::default()
            }),
            ..Corpus::default()
        };
        let out = render(&c);
        let one = out.find("### Revision 1 — accepted").unwrap();
        let two = out.find("### Revision 2 — accepted").unwrap();
        assert!(one < two);
        assert!(out.contains("predecessor revision 1"));
        assert!(out.contains("- **Diff against its predecessor:** P-PHASE-0 +open x\n"));
        assert!(out.contains("- **Phases (1):** P-PHASE-0 Start\n"));
    }

    #[test]
    fn the_history_expands_what_the_master_document_replaces() {
        let c = Corpus {
            program: "P".into(),
            subjects: vec![
                s("A", "superseded", Some("B")),
                s("B", "superseded", Some("C")),
                s("C", "current", None),
            ],
            ..Corpus::default()
        };
        let out = render(&c);
        assert!(out.contains("- A → B → C\n"), "{out}");
        assert!(out.contains("A INTENT\n"));
        assert!(out.contains("B INTENT\n"));
    }
}
