// SPDX-License-Identifier: AGPL-3.0-or-later
//! The generated Warrant Overview — the corpus-wide status projection (SAS §17.5
//! `status`, §20.4).
//!
//! This is the list work gets knocked off. It is compiled from the Warrants
//! themselves, so it cannot claim a Warrant exists that does not, or omit one
//! that does — which is exactly the failure a hand-maintained roadmap has.
//!
//! # Status is real, and it is derived
//!
//! §24's five dimensions are implemented (OW-WAR-0008), so the status column is
//! no longer absent. It reports `derived` rather than `recorded` because nothing
//! journals transitions yet (OW-WAR-0031), and every Warrant derives to `draft`
//! because authorization does not exist until OW-WAR-0009.
//!
//! Forty Warrants all reading `draft` is the honest answer, not a bug.
//!
//! **Milestone progress.** Milestones now parse (OW-WAR-0007), so the column
//! reports how many are DECLARED — never how many are met. Completion needs the
//! state model and gate runs, and a column that looked like progress would be
//! read as progress.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use serde::Serialize;

/// One Warrant, as much as can be honestly reported today.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct WarrantSummary {
    pub alias: String,
    pub uuid: String,
    pub title: String,
    pub profile: String,
    pub assurance_level: String,
    /// `sas://` refs from `[[implements]]`.
    pub implements: Vec<String>,
    /// `roadmap://` refs.
    pub roadmap: Vec<String>,
    /// Parent aliases where resolvable in this corpus, else the raw ref.
    pub parents: Vec<String>,
    pub atom_count: usize,
    pub source: String,
    /// `(milestones, stages)` when the graph parses. Still NOT whether any
    /// milestone is MET — that needs the state model (OW-WAR-0008) and gate runs
    /// (OW-WAR-0020). A count of declarations is not a count of achievements.
    pub milestone_count: Option<(usize, usize)>,
    /// The five §24 dimensions, with provenance. Derived until OW-WAR-0031.
    pub state: openwarrant_core::WarrantState,
}

/// Render the Warrant Overview.
pub fn render(summaries: &[WarrantSummary]) -> String {
    let mut sorted: Vec<&WarrantSummary> = summaries.iter().collect();
    sorted.sort_by(|a, b| a.alias.cmp(&b.alias));

    let mut out = String::new();
    out.push_str(
        "<!--\nGENERATED BY OPENWARRANT. DO NOT EDIT.\nSource: the Warrants under the configured warrants path.\n-->\n\n",
    );
    out.push_str("# Warrant Overview\n\n");

    if sorted.is_empty() {
        out.push_str("No Warrants are recorded yet.\n");
        return out;
    }

    let _ = writeln!(out, "{} Warrant(s) in this repository.\n", sorted.len());

    out.push_str("## Summary\n\n");
    out.push_str("| Warrant | Title | Phase | Currency | Standing | Assurance | Milestones |\n");
    out.push_str("|---|---|---|---|---|---|---|\n");
    for w in &sorted {
        let _ = writeln!(
            out,
            "| [{alias}]({source}) | {title} | `{phase}` | `{currency}` | `{standing}` | `{assurance}` | {ms} |",
            alias = w.alias,
            source = w.source,
            title = w.title,
            phase = w.state.phase,
            currency = w.state.currency,
            standing = w.state.standing,
            assurance = w.assurance_level,
            ms = match w.milestone_count {
                Some((m, st)) => format!("{m}M / {st}S"),
                None => "—".to_owned(),
            },
        );
    }

    // State provenance, stated once rather than repeated per row.
    let derived = sorted
        .iter()
        .filter(|w| w.state.provenance == openwarrant_core::Provenance::Derived)
        .count();
    if derived > 0 {
        let _ = write!(
            out,
            "\n> **{derived} of {} states are DERIVED, not recorded.** Nothing journals \
             transitions yet (OW-WAR-0031), and authorization does not exist until \
             OW-WAR-0009 — so no Warrant has left `draft`. A later phase would have to \
             be invented.\n",
            sorted.len()
        );
    }

    // Requirement coverage. This is a claim about which requirements a Warrant
    // SAYS it implements — not about whether it does. §34.3 makes requirement
    // status a separate thing from a Warrant's own assertion, and conflating the
    // two would let a manifest grant itself coverage.
    let mut claimed: BTreeSet<String> = BTreeSet::new();
    for w in &sorted {
        for r in &w.implements {
            claimed.insert(r.trim_start_matches("sas://").to_owned());
        }
    }
    let _ = write!(
        out,
        "\n## Claimed SAS requirement coverage\n\n\
         {} distinct requirement(s) are claimed by at least one Warrant.\n\n",
        claimed.len()
    );
    out.push_str(
        "> **Claimed, not verified.** A Warrant declaring `[[implements]]` is an \
         assertion by its author. §34.3 treats requirement status as a separate \
         record; nothing here checks that the requirement is actually met.\n\n",
    );
    for r in &claimed {
        let by: Vec<&str> = sorted
            .iter()
            .filter(|w| {
                w.implements
                    .iter()
                    .any(|i| i.trim_start_matches("sas://") == r)
            })
            .map(|w| w.alias.as_str())
            .collect();
        let _ = writeln!(out, "- `{r}` — {}", by.join(", "));
    }

    out.push_str("\n## Relations\n\n");
    for w in &sorted {
        if w.parents.is_empty() && w.roadmap.is_empty() {
            continue;
        }
        let _ = write!(out, "- **{}**", w.alias);
        if !w.parents.is_empty() {
            let _ = write!(out, " · parent: {}", w.parents.join(", "));
        }
        if !w.roadmap.is_empty() {
            let _ = write!(out, " · roadmap: {}", w.roadmap.join(", "));
        }
        out.push('\n');
    }

    let recorded = sorted
        .iter()
        .filter(|w| w.state.provenance == openwarrant_core::Provenance::Recorded)
        .count();
    out.push_str("\n## Not reported here\n\n");
    if derived > 0 {
        let _ = writeln!(
            out,
            "- **Recorded state.** {derived} phase(s) are DERIVED from the record's shape, \
             not read from a journalled transition; {recorded} are read from a journal \
             (§66, OW-WAR-0031)."
        );
    } else {
        let _ = writeln!(
            out,
            "- **Recorded state.** Every phase is read from the Warrant's journal (§66, \
             OW-WAR-0031); a `backfilled` event is a reconstruction from records, and \
             says so in its payload."
        );
    }
    out.push_str(
        "- **Milestone progress** — the column counts DECLARED milestones and \
         stages. Nothing here says any of them is met.\n\
         - **Resolution** — a phase of `resolved` is read from a §56.2 record; every \
         other phase says nothing about whether a Warrant is done.\n",
    );

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn w(alias: &str, implements: &[&str]) -> WarrantSummary {
        WarrantSummary {
            alias: alias.to_owned(),
            uuid: format!("uuid-{alias}"),
            title: format!("Title of {alias}"),
            profile: "delivery".to_owned(),
            assurance_level: "basic".to_owned(),
            implements: implements.iter().map(|s| format!("sas://{s}")).collect(),
            roadmap: vec!["roadmap://OW-PHASE-1/x".to_owned()],
            parents: vec![],
            atom_count: 5,
            source: format!("docs/warrants/{alias}/manifest.toml"),
            milestone_count: Some((3, 3)),
            state: openwarrant_core::WarrantState::draft(openwarrant_core::Provenance::Derived),
        }
    }

    #[test]
    fn lists_every_warrant() {
        let out = render(&[w("OW-WAR-0001", &["RQ-070"]), w("OW-WAR-0002", &["RQ-010"])]);
        assert!(out.contains("2 Warrant(s)"));
        assert!(out.contains("OW-WAR-0001"));
        assert!(out.contains("OW-WAR-0002"));
    }

    #[test]
    fn requirement_coverage_attributes_each_requirement_to_its_warrants() {
        let out = render(&[
            w("OW-WAR-0001", &["RQ-070", "RQ-064"]),
            w("OW-WAR-0002", &["RQ-070"]),
        ]);
        assert!(out.contains("2 distinct requirement(s)"));
        // RQ-070 is claimed by both and must name both.
        let line = out
            .lines()
            .find(|l| l.starts_with("- `RQ-070`"))
            .expect("coverage line");
        assert!(line.contains("OW-WAR-0001") && line.contains("OW-WAR-0002"));
    }

    /// The overview must not imply it verified anything.
    #[test]
    fn coverage_is_labelled_as_claimed_not_verified() {
        let out = render(&[w("OW-WAR-0001", &["RQ-070"])]);
        assert!(out.contains("Claimed, not verified"));
    }

    /// The status column is real now (OW-WAR-0008), and its DERIVED provenance
    /// must be stated — otherwise a derived phase reads as a recorded one.
    ///
    /// This test replaced `no_lifecycle_status_is_rendered`, which asserted the
    /// column's absence. That test failed the moment the column arrived, which
    /// is a test doing its job: the behaviour changed, so the assertion had to.
    #[test]
    fn derived_state_is_reported_and_labelled_derived() {
        let out = render(&[w("OW-WAR-0001", &["RQ-070"])]);
        assert!(out.contains("| `draft` |"), "the phase is reported");
        assert!(
            out.contains("DERIVED, not recorded"),
            "provenance must be stated, or a derived phase reads as recorded"
        );
    }

    /// A recorded state must not carry the derived banner.
    #[test]
    fn recorded_state_is_not_labelled_derived() {
        let mut only = w("OW-WAR-0001", &["RQ-070"]);
        only.state = openwarrant_core::WarrantState::draft(openwarrant_core::Provenance::Recorded);
        let out = render(&[only]);
        assert!(
            !out.contains("DERIVED, not recorded"),
            "a recorded state must not be disclaimed as derived"
        );
    }

    #[test]
    fn output_is_independent_of_input_order() {
        let a = w("OW-WAR-0001", &["RQ-070"]);
        let b = w("OW-WAR-0002", &["RQ-010"]);
        assert_eq!(render(&[a.clone(), b.clone()]), render(&[b, a]));
    }

    #[test]
    fn an_empty_corpus_says_so() {
        assert!(render(&[]).contains("No Warrants are recorded yet."));
    }
}
