// SPDX-License-Identifier: AGPL-3.0-or-later
//! The generated Warrant Overview — the corpus-wide status projection (SAS §17.5
//! `status`, §20.4).
//!
//! This is the list work gets knocked off. It is compiled from the Warrants
//! themselves, so it cannot claim a Warrant exists that does not, or omit one
//! that does — which is exactly the failure a hand-maintained roadmap has.
//!
//! # What it deliberately does NOT report
//!
//! **Lifecycle state.** §24 decomposes state into phase, condition, outcome,
//! currency, and standing, and none of that is implemented yet (OW-WAR-0008).
//! Rendering a "status" column now would mean inventing one — most likely by
//! guessing from whether files exist — and a status column that is guessed is
//! worse than absent, because a reader will act on it.
//!
//! **Milestone progress.** Milestones are not parsed yet (OW-WAR-0007), so the
//! count below is of DECLARED milestone atoms, not of met milestones.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use serde::Serialize;

/// One Warrant, as much as can be honestly reported today.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct WarrantSummary {
    pub alias: String,
    pub uuid: String,
    pub title: String,
    pub profile: String,
    pub assurance_level: String,
    /// `sas://` refs from `[[implements]]`.
    pub implements: Vec<String>,
    /// `roadmap://` refs.
    pub roadmap: Vec<String>,
    /// Parent aliases where resolvable in this corpus, else the raw ref.
    pub parents: Vec<String>,
    pub atom_count: usize,
    pub source: String,
    /// Whether this Warrant carries a milestones atom at all. Not whether any
    /// milestone is met — nothing can answer that yet.
    pub declares_milestones: bool,
}

/// Render the Warrant Overview.
pub fn render(summaries: &[WarrantSummary]) -> String {
    let mut sorted: Vec<&WarrantSummary> = summaries.iter().collect();
    sorted.sort_by(|a, b| a.alias.cmp(&b.alias));

    let mut out = String::new();
    out.push_str(
        "<!--\nGENERATED BY OPENWARRANT. DO NOT EDIT.\nSource: the Warrants under the configured warrants path.\n-->\n\n",
    );
    out.push_str("# Warrant Overview\n\n");

    if sorted.is_empty() {
        out.push_str("No Warrants are recorded yet.\n");
        return out;
    }

    let _ = writeln!(out, "{} Warrant(s) in this repository.\n", sorted.len());

    out.push_str("## Summary\n\n");
    out.push_str("| Warrant | Title | Profile | Assurance | Atoms | Milestones | Implements |\n");
    out.push_str("|---|---|---|---|---:|---|---|\n");
    for w in &sorted {
        let implements = if w.implements.is_empty() {
            "—".to_owned()
        } else {
            w.implements
                .iter()
                .map(|r| r.trim_start_matches("sas://").to_owned())
                .collect::<Vec<_>>()
                .join(", ")
        };
        let _ = writeln!(
            out,
            "| [{alias}]({source}) | {title} | `{profile}` | `{assurance}` | {atoms} | {ms} | {implements} |",
            alias = w.alias,
            source = w.source,
            title = w.title,
            profile = w.profile,
            assurance = w.assurance_level,
            atoms = w.atom_count,
            ms = if w.declares_milestones {
                "declared"
            } else {
                "—"
            },
        );
    }

    // Requirement coverage. This is a claim about which requirements a Warrant
    // SAYS it implements — not about whether it does. §34.3 makes requirement
    // status a separate thing from a Warrant's own assertion, and conflating the
    // two would let a manifest grant itself coverage.
    let mut claimed: BTreeSet<String> = BTreeSet::new();
    for w in &sorted {
        for r in &w.implements {
            claimed.insert(r.trim_start_matches("sas://").to_owned());
        }
    }
    let _ = write!(
        out,
        "\n## Claimed SAS requirement coverage\n\n\
         {} distinct requirement(s) are claimed by at least one Warrant.\n\n",
        claimed.len()
    );
    out.push_str(
        "> **Claimed, not verified.** A Warrant declaring `[[implements]]` is an \
         assertion by its author. §34.3 treats requirement status as a separate \
         record; nothing here checks that the requirement is actually met.\n\n",
    );
    for r in &claimed {
        let by: Vec<&str> = sorted
            .iter()
            .filter(|w| {
                w.implements
                    .iter()
                    .any(|i| i.trim_start_matches("sas://") == r)
            })
            .map(|w| w.alias.as_str())
            .collect();
        let _ = writeln!(out, "- `{r}` — {}", by.join(", "));
    }

    out.push_str("\n## Relations\n\n");
    for w in &sorted {
        if w.parents.is_empty() && w.roadmap.is_empty() {
            continue;
        }
        let _ = write!(out, "- **{}**", w.alias);
        if !w.parents.is_empty() {
            let _ = write!(out, " · parent: {}", w.parents.join(", "));
        }
        if !w.roadmap.is_empty() {
            let _ = write!(out, " · roadmap: {}", w.roadmap.join(", "));
        }
        out.push('\n');
    }

    out.push_str(
        "\n## Not reported here\n\n\
         - **Lifecycle state** (§24: phase, condition, outcome, currency, standing) \
         is not implemented, so no Warrant has a status. A guessed status column \
         would be acted on.\n\
         - **Milestone progress** — milestones are not parsed, so the column above \
         says only whether a milestones atom is DECLARED.\n\
         - **Resolution** — nothing here says a Warrant is done.\n",
    );

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn w(alias: &str, implements: &[&str]) -> WarrantSummary {
        WarrantSummary {
            alias: alias.to_owned(),
            uuid: format!("uuid-{alias}"),
            title: format!("Title of {alias}"),
            profile: "delivery".to_owned(),
            assurance_level: "basic".to_owned(),
            implements: implements.iter().map(|s| format!("sas://{s}")).collect(),
            roadmap: vec!["roadmap://OW-PHASE-1/x".to_owned()],
            parents: vec![],
            atom_count: 5,
            source: format!("docs/warrants/{alias}/manifest.toml"),
            declares_milestones: true,
        }
    }

    #[test]
    fn lists_every_warrant() {
        let out = render(&[w("OW-WAR-0001", &["RQ-070"]), w("OW-WAR-0002", &["RQ-010"])]);
        assert!(out.contains("2 Warrant(s)"));
        assert!(out.contains("OW-WAR-0001"));
        assert!(out.contains("OW-WAR-0002"));
    }

    #[test]
    fn requirement_coverage_attributes_each_requirement_to_its_warrants() {
        let out = render(&[
            w("OW-WAR-0001", &["RQ-070", "RQ-064"]),
            w("OW-WAR-0002", &["RQ-070"]),
        ]);
        assert!(out.contains("2 distinct requirement(s)"));
        // RQ-070 is claimed by both and must name both.
        let line = out
            .lines()
            .find(|l| l.starts_with("- `RQ-070`"))
            .expect("coverage line");
        assert!(line.contains("OW-WAR-0001") && line.contains("OW-WAR-0002"));
    }

    /// The overview must not imply it verified anything.
    #[test]
    fn coverage_is_labelled_as_claimed_not_verified() {
        let out = render(&[w("OW-WAR-0001", &["RQ-070"])]);
        assert!(out.contains("Claimed, not verified"));
    }

    /// A status column would be invented, so it must not appear at all.
    #[test]
    fn no_lifecycle_status_is_rendered() {
        let out = render(&[w("OW-WAR-0001", &["RQ-070"])]);
        assert!(
            !out.contains("| Status |"),
            "a status column would be guessed; §24 is not implemented"
        );
        assert!(
            out.contains("Lifecycle state"),
            "the absence must be stated"
        );
    }

    #[test]
    fn output_is_independent_of_input_order() {
        let a = w("OW-WAR-0001", &["RQ-070"]);
        let b = w("OW-WAR-0002", &["RQ-010"]);
        assert_eq!(render(&[a.clone(), b.clone()]), render(&[b, a]));
    }

    #[test]
    fn an_empty_corpus_says_so() {
        assert!(render(&[]).contains("No Warrants are recorded yet."));
    }
}
