// SPDX-License-Identifier: Apache-2.0
// Generated by war schemas. Do not edit.
// Structural types only; retain JSON Schema runtime validation.
type Def_Affected = ({ "depth": (number); "id": (string); "revision": (string); "source": (string); "type": (string); "via": (Def_Relation); });
type Def_Document = ({ "because": (Array<(string)>); "id": (string); "kind": (string); });
type Def_Evaluation = ({ "bound_revision"?: ((string)) | ((null)); "current_revision": (string); "obligation": (string); "reads": (string); "target": (string); "verdict"?: ((string)) | ((null)); });
type Def_Phase = ({ "achieved"?: ((string)) | ((null)); "id": (string); "via": (Array<(string)>); });
type Def_Projection = ({ "path": (string); "scope": (string); "selects": (Array<(string)>); });
type Def_Relation = ({ "from": (string); "kind": (string); "to": (string); "to_revision"?: ((string)) | ((null)); });
type Def_Subject = ({ "id": (string); "revision": (string); "source": (string); "type": (string); });
export type Document = ({ "affected": (Array<(Def_Affected)>); "basis_digest": (string); "documents": (Array<(Def_Document)>); "evaluations": (Array<(Def_Evaluation)>); "inert": (Array<(Def_Relation)>); "phases": (Array<(Def_Phase)>); "projections": (Array<(Def_Projection)>); "record": (Def_Subject); "schema": (string); });
