// SPDX-License-Identifier: Apache-2.0
// Generated by war schemas. Do not edit.
// Structural types only; retain JSON Schema runtime validation.
type Def_Earlier = ({ "count": (number); "first": (string); "last": (string); "text": (string); "warrants"?: (Array<(string)>); [key: string]: unknown; });
type Def_Entry = ({ "commit"?: ((string)) | ((null)); "date": (string); "source": (Def_Source); "warrant"?: ((string)) | ((null)); "why": (string); [key: string]: unknown; });
type Def_Source = ((("commit") & (string)) | (("deterministic") & (string)) | (("agent") & (string)) | (("agent-trace") & (string)) | (("git-ai") & (string)));
export type Document = ({ "atom": (string); "earlier"?: (((Def_Earlier)) | ((null))); "entries": (Array<(Def_Entry)>); "path": (string); "schema": (string); [key: string]: unknown; });
