// SPDX-License-Identifier: Apache-2.0
// Generated by war schemas. Do not edit.
// Structural types only; retain JSON Schema runtime validation.
type Def_BasisEcho = ({ "digest": (string); "id": (string); });
type Def_HostDiagnostic = ({ "message": (string); "rule": (string); "severity": (string); "subject": (string); });
type Def_Limits = ({ "input_bytes": (number); "json_nodes": (number); "member_bytes": (number); "members": (number); "output_bytes": (number); "projections": (number); });
type Def_Model = ({ "basis_digest": (string); "diagnostics": (Array<(Def_ModelDiagnostic)>); "records": (Array<(Def_Record)>); "relations": (Array<(Def_Relation)>); "schema": (string); "states": (Array<(Def_State)>); });
type Def_ModelDiagnostic = ({ "message": (string); "record": (string); "rule": (string); });
type Def_ObservationUse = ({ "authenticated": (boolean); "git_missing": (number); "git_supplied": (number); "git_used": (number); "signatures_missing": (number); "signatures_supplied": (number); "signatures_used": (number); });
type Def_Projection = ({ "digest"?: ((string)) | ((null)); "kind": (string); "path"?: ((string)) | ((null)); "reason"?: ((string)) | ((null)); "status": (string); "subject": (string); "utf8"?: ((string)) | ((null)); });
type Def_Record = ({ "governed_by"?: ((string)) | ((null)); "id": (string); "revision": (string); "source": (string); "type": (string); });
type Def_Refusal = ({ "message": (string); "rule": (string); });
type Def_Relation = ({ "from": (string); "kind": (string); "to": (string); "to_revision"?: ((string)) | ((null)); });
type Def_State = ({ "kind": (string); "provenance": (string); "record": (string); "value": (string); });
export type Document = ({ "basis"?: (((Def_BasisEcho)) | ((null))); "diagnostics": (Array<(Def_HostDiagnostic)>); "limits": (Def_Limits); "model"?: (((Def_Model)) | ((null))); "model_digest"?: ((string)) | ((null)); "observations": (Def_ObservationUse); "outcome": (string); "projections": (Array<(Def_Projection)>); "protocol": (string); "refusal"?: (((Def_Refusal)) | ((null))); "version": (number); });
