// SPDX-License-Identifier: Apache-2.0
// Generated by war schemas. Do not edit.
// Structural types only; retain JSON Schema runtime validation.
type Def_Basis = ({ "digest": (string); "id": (string); "members": (Array<(Def_Member)>); });
type Def_DeclaredLimits = ({ "input_bytes"?: ((number)) | ((null)); "json_nodes"?: ((number)) | ((null)); "member_bytes"?: ((number)) | ((null)); "members"?: ((number)) | ((null)); "output_bytes"?: ((number)) | ((null)); "projections"?: ((number)) | ((null)); });
type Def_GitObservation = ({ "args": (Array<(string)>); "error"?: ((string)) | ((null)); "stdout_hex"?: ((string)) | ((null)); });
type Def_Member = ({ "digest": (string); "hex"?: ((string)) | ((null)); "path": (string); "utf8"?: ((string)) | ((null)); "withheld"?: (boolean); });
type Def_Node = ({ "id": (string); "jurisdiction"?: ((string)) | ((null)); "revision": (string); "source": (string); "type": (string); });
type Def_Observations = ({ "git"?: (Array<(Def_GitObservation)>); "signatures"?: (Array<(Def_SignatureObservation)>); });
type Def_Options = ({ "limits"?: (((Def_DeclaredLimits)) | ((null))); "projections"?: (Array<(Def_ProjectionRequest)>); });
type Def_Profile = ({ "digest": (string); "name": (string); "utf8": (string); });
type Def_ProjectionRequest = ({ "kind": (string); "subject": (string); });
type Def_Relation = ({ "from": (string); "kind": (string); "to": (string); "to_revision"?: ((string)) | ((null)); });
type Def_SignatureObservation = ({ "key": (string); "reason"?: ((string)) | ((null)); "verdict": (string); });
export type Document = ({ "basis": (Def_Basis); "nodes": (Array<(Def_Node)>); "observations"?: (Def_Observations); "options"?: (Def_Options); "profiles": (Array<(Def_Profile)>); "protocol": (string); "relations": (Array<(Def_Relation)>); "version": (number); });
