// SPDX-License-Identifier: Apache-2.0
// Generated by war schemas. Do not edit.
// Structural types only; retain JSON Schema runtime validation.
type Def_Selected = ({ "bytes": (number); "id": (string); "revision": (string); "source": (string); "type": (string); });
type Def_Subject = ({ "id": (string); "kind": (string); "revision"?: ((string)) | ((null)); "seeds": (Array<(string)>); "source"?: ((string)) | ((null)); "title": (string); });
type Def_Template = ({ "profile": (string); "revision": (string); });
type Def_Trace = ({ "end_line": (number); "id": (string); "origin": (string); "revision"?: ((string)) | ((null)); "start_line": (number); });
export type Document = ({ "bytes": (number); "content": (string); "digest": (string); "max_bytes"?: ((number)) | ((null)); "mentions": (Array<(string)>); "projection": (string); "renderer": (string); "schema": (string); "selects": (Array<(Def_Selected)>); "subject": (Def_Subject); "template": (Def_Template); "trace": (Array<(Def_Trace)>); });
