// SPDX-License-Identifier: Apache-2.0
// Generated by war schemas. Do not edit.
// Structural types only; retain JSON Schema runtime validation.
type Def_Placement = ({ "phase": (string); "slug"?: ((string)) | ((null)); "warrant": (string); });
type Def_Retired = ({ "lineage": (string); "path": (string); });
type Def_RoadmapAtomRef = ({ "ordinal": (number); "path": (string); "role": (string); });
export type Document = ({ "atoms"?: (Array<(Def_RoadmapAtomRef)>); "placement"?: (Array<(Def_Placement)>); "prefix": (string); "program": (string); "retires"?: (Array<(Def_Retired)>); "schema": (string); "uuid": (string); });
