// SPDX-License-Identifier: Apache-2.0
// Generated by war schemas. Do not edit.
// Structural types only; retain JSON Schema runtime validation.
type Def_Dimension = ({ "denominator"?: ((number)) | ((null)); "detail": (string); "id": (string); "numerator"?: ((number)) | ((null)); "points": (number); "status": (Def_Status); "weight": (number); [key: string]: unknown; });
type Def_Level = ({ "name": (string); "number": (number); [key: string]: unknown; });
type Def_Status = ((("measured") & (string)) | (("unknown") & (string)));
type Def_Window = ({ "baseline"?: ((string)) | ((null)); "limit": (number); [key: string]: unknown; });
export type Document = ({ "commit"?: ((string)) | ((null)); "dimensions": (Array<(Def_Dimension)>); "level": (Def_Level); "next_steps": (Array<(string)>); "schema": (string); "score": (number); "weights": (string); "window": (Def_Window); [key: string]: unknown; });
