// SPDX-License-Identifier: Apache-2.0
// Generated by war schemas. Do not edit.
// Structural types only; retain JSON Schema runtime validation.
type Def_Dimension = ({ "denominator"?: ((number)) | ((null)); "detail": (string); "id": (string); "numerator"?: ((number)) | ((null)); "points": (number); "status": (Def_Status); "weight": (number); [key: string]: unknown; });
type Def_Level = ({ "name": (string); "number": (number); [key: string]: unknown; });
type Def_Predicate = ({ "dimensions": (Array<(Def_Dimension)>); "level": (Def_Level); "producer"?: (((Def_Producer)) | ((null))); "score": (number); "weights": (string); "window"?: (((Def_Window)) | ((null))); [key: string]: unknown; });
type Def_Producer = ({ "name": (string); "version": (string); [key: string]: unknown; });
type Def_Status = ((("measured") & (string)) | (("unknown") & (string)));
type Def_Subject = ({ "digest": ({ [key: string]: (string); }); "name": (string); [key: string]: unknown; });
type Def_Window = ({ "baseline"?: ((string)) | ((null)); "limit": (number); [key: string]: unknown; });
export type Document = ({ "_type": (string); "predicate": (Def_Predicate); "predicateType": (string); "subject": (Array<(Def_Subject)>); [key: string]: unknown; });
