// SPDX-License-Identifier: Apache-2.0
// Generated by war schemas. Do not edit.
// Structural types only; retain JSON Schema runtime validation.
type Def_Budget = ({ "budget_tokens": (number); "max_deliverables": (number); "max_stages": (number); "wall_time_seconds": (number); });
export type Document = ({ "assurance": (string); "budget": (Def_Budget); "expires_at": (string); "gates": (Array<(string)>); "id": (string); "max_warrants": (number); "meaning": (string); "paths": (Array<(string)>); "profile": (string); "revision": (number); "schema": (string); });
