// SPDX-License-Identifier: Apache-2.0
//! The file ledger (OW-WAR-0148 M17, decision 24; docs/LEDGER.md): why each
//! file changed, kept beside the code.
//!
//! # Two forms, one source
//!
//! - **Atoms**, committed: one small Markdown file per source file, at
//!   `docs/ledger/<path>.md` (`[ledger] dir`). Each line is one change: its
//!   date, commit, Warrant and why. Past the last `keep` entries (default 3)
//!   or a token budget, older entries fold into one `earlier` line. Git keeps
//!   the full history; the atom keeps the curated reason.
//! - **`.openwarrant/ledger.jsonl`**, regenerated by `war admin compile` and
//!   never committed: one JSON line per file, so an agent reads every file's
//!   why in one go. The directory ignores the file itself, and `war check`
//!   refuses a commit that tracks it (`ledger.committed`).
//!
//! # Three writer modes
//!
//! `war admin ledger record` writes an entry for each file a commit touched.
//! Its why comes from, by `[ledger] mode`:
//!
//! - `commit` (the default): the commit's `Ledger:` trailer (`Ledger: <path>:
//!   <why>` for one file), else its body's first paragraph; falling back to
//!   `deterministic` when the message has neither;
//! - `deterministic`: the cited Warrant's title (`Warrant:` trailer), else the
//!   commit subject;
//! - `agent`: the text the agent gives (`--why`), asked for at `war done`.
//!
//! Agent Trace records and git-ai notes read in and write out through
//! [`interop`].

pub mod cmd;
pub mod interop;

use std::collections::{BTreeMap, BTreeSet};

use camino::{Utf8Path, Utf8PathBuf};
use serde::{Deserialize, Serialize};

use crate::diagnostic::{Diagnostic, Report};
use crate::go::git::git;
use crate::repo::{RepoError, Repository};
use crate::vfs as fs;

/// Where the atoms live unless `[ledger] dir` says otherwise.
pub const DEFAULT_DIR: &str = "docs/ledger";
/// The compiled, gitignored form.
pub const JSONL: &str = ".openwarrant/ledger.jsonl";
/// What `war admin compile` writes under `.openwarrant/`, ignored by the
/// directory's own `.gitignore`.
pub const IGNORED: &[&str] = &["ledger.jsonl", "score/"];
/// Entries an atom keeps before it folds older ones (decision 24).
pub const DEFAULT_KEEP: usize = 3;
/// The JSONL line's schema family.
pub const LINE_SCHEMA: &str = "oh.war/ledger-file/v1";
/// The longest an `earlier` line's reasons grow before they are cut.
const SUMMARY_TEXT_MAX: usize = 400;
/// The longest one why is kept, in characters.
const WHY_MAX: usize = 300;

/// Where a why came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[serde(rename_all = "kebab-case")]
pub enum Source {
    /// A `Ledger:` trailer or the commit body.
    Commit,
    /// The Warrant's title or the commit subject.
    Deterministic,
    /// Text an agent gave at done.
    Agent,
    /// Read from an Agent Trace record.
    AgentTrace,
    /// Read from a git-ai note (`refs/notes/ai`).
    GitAi,
}

impl Source {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Commit => "commit",
            Self::Deterministic => "deterministic",
            Self::Agent => "agent",
            Self::AgentTrace => "agent-trace",
            Self::GitAi => "git-ai",
        }
    }

    fn parse(s: &str) -> Option<Self> {
        Some(match s {
            "commit" => Self::Commit,
            "deterministic" => Self::Deterministic,
            "agent" => Self::Agent,
            "agent-trace" => Self::AgentTrace,
            "git-ai" => Self::GitAi,
            _ => return None,
        })
    }
}

/// The writer mode `[ledger] mode` names.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Mode {
    #[default]
    Commit,
    Deterministic,
    Agent,
}

impl Mode {
    /// # Errors
    /// A word that names no mode.
    pub fn parse(s: &str) -> Result<Self, String> {
        match s {
            "commit" => Ok(Self::Commit),
            "deterministic" => Ok(Self::Deterministic),
            "agent" => Ok(Self::Agent),
            other => Err(format!(
                "[ledger] mode = {other:?} names no writer mode; it is commit, deterministic or agent"
            )),
        }
    }

    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Commit => "commit",
            Self::Deterministic => "deterministic",
            Self::Agent => "agent",
        }
    }
}

/// `[ledger]` in openwarrant.toml.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Config {
    pub dir: String,
    pub mode: Mode,
    /// Entries kept before folding, when no token budget is set.
    pub keep: usize,
    /// Fold until an atom fits this many tokens (about four characters
    /// each), keeping at least one entry. Wins over `keep` when set.
    pub token_budget: Option<usize>,
    /// Directories never recorded besides the ledger's own: the Warrant and
    /// ticket trees, which journal themselves ([`Config::scoped`]).
    pub skip: Vec<String>,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            dir: DEFAULT_DIR.to_owned(),
            mode: Mode::Commit,
            keep: DEFAULT_KEEP,
            token_budget: None,
            skip: Vec::new(),
        }
    }
}

impl Config {
    /// The table, with the repository's record trees added to what is never
    /// recorded.
    #[must_use]
    pub fn scoped(mut self, repo: &Repository) -> Self {
        self.skip
            .push(repo.config.paths.warrants.trim_end_matches('/').to_owned());
        if let Ok(store) = crate::ticket::Store::open(repo, None) {
            self.skip.push(repo.relative(&store.dir));
        }
        self
    }

    /// The `[ledger]` table, or the defaults when there is none.
    ///
    /// # Errors
    /// A table that does not read: a key of the wrong type, an unknown mode,
    /// `keep = 0` or `token_budget = 0`.
    pub fn read(root: &Utf8Path) -> Result<Self, String> {
        let path = root.join(crate::init::CONFIG_FILE);
        let Ok(text) = fs::read_to_string(&path) else {
            return Ok(Self::default());
        };
        Self::from_text(&text)
    }

    /// # Errors
    /// See [`Self::read`].
    pub fn from_text(text: &str) -> Result<Self, String> {
        let doc: toml::Table = text
            .parse()
            .map_err(|e| format!("openwarrant.toml does not parse: {e}"))?;
        let mut out = Self::default();
        let Some(t) = doc.get("ledger") else {
            return Ok(out);
        };
        let t = t
            .as_table()
            .ok_or_else(|| "[ledger] is not a table".to_owned())?;
        for (k, v) in t {
            match k.as_str() {
                "dir" => {
                    let d = v
                        .as_str()
                        .ok_or_else(|| "[ledger] dir is not a string".to_owned())?;
                    if d.is_empty() || d.starts_with('/') || d.split('/').any(|p| p == "..") {
                        return Err(format!(
                            "[ledger] dir = {d:?} is not a relative path inside the repository"
                        ));
                    }
                    out.dir = d.trim_end_matches('/').to_owned();
                }
                "mode" => {
                    out.mode = Mode::parse(
                        v.as_str()
                            .ok_or_else(|| "[ledger] mode is not a string".to_owned())?,
                    )?;
                }
                "keep" => {
                    let n = v
                        .as_integer()
                        .ok_or_else(|| "[ledger] keep is not a number".to_owned())?;
                    if n < 1 {
                        return Err(format!(
                            "[ledger] keep = {n}: an atom keeps at least 1 entry; the default is {DEFAULT_KEEP}"
                        ));
                    }
                    out.keep = usize::try_from(n).unwrap_or(usize::MAX);
                }
                "token_budget" => {
                    let n = v
                        .as_integer()
                        .ok_or_else(|| "[ledger] token_budget is not a number".to_owned())?;
                    if n < 1 {
                        return Err(format!(
                            "[ledger] token_budget = {n}: a budget is at least 1 token; remove the key to fold by entry count"
                        ));
                    }
                    out.token_budget = Some(usize::try_from(n).unwrap_or(usize::MAX));
                }
                other => {
                    return Err(format!(
                        "[ledger] {other} is not a key war reads: dir, mode, keep, token_budget"
                    ));
                }
            }
        }
        Ok(out)
    }
}

/// One change to one file.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct Entry {
    /// `YYYY-MM-DD`: the commit's committer date, or the day an uncommitted
    /// change was recorded.
    pub date: String,
    /// The full commit id, or absent for a change recorded before its commit.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub commit: Option<String>,
    /// The Warrant the change cites, when it cites one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub warrant: Option<String>,
    pub source: Source,
    pub why: String,
}

/// Older entries, folded.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct Earlier {
    pub count: usize,
    pub first: String,
    pub last: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub warrants: Vec<String>,
    /// The folded reasons, joined by ` | ` and cut at 400 characters.
    pub text: String,
}

/// One file's ledger.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct Atom {
    /// The file, repository-relative.
    pub path: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub earlier: Option<Earlier>,
    /// Oldest first.
    pub entries: Vec<Entry>,
}

/// One line of `.openwarrant/ledger.jsonl`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct Line {
    pub schema: String,
    /// The file, repository-relative.
    pub path: String,
    /// The atom it compiles from.
    pub atom: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub earlier: Option<Earlier>,
    pub entries: Vec<Entry>,
}

const INTRO: &str = "Why this file changed, oldest first (`war admin ledger record`). Older \
                     entries fold into the `earlier` line; git keeps the full history.";

/// One line, every newline and run of spaces collapsed, cut at `max`.
#[must_use]
pub fn one_line(text: &str, max: usize) -> String {
    let s = text.split_whitespace().collect::<Vec<_>>().join(" ");
    cut(&s, max)
}

fn cut(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        return s.to_owned();
    }
    let mut out: String = s.chars().take(max.saturating_sub(1)).collect();
    out.push('…');
    out
}

impl Atom {
    /// The atom's Markdown, as committed.
    #[must_use]
    pub fn render(&self) -> String {
        let mut md = format!("# Ledger: `{}`\n\n{INTRO}\n\n", self.path);
        if let Some(e) = &self.earlier {
            md.push_str(&format!(
                "- earlier: {} change(s), {}..{}; Warrants {}; {}\n",
                e.count,
                e.first,
                e.last,
                if e.warrants.is_empty() {
                    "none".to_owned()
                } else {
                    e.warrants.join(", ")
                },
                e.text
            ));
        }
        for e in &self.entries {
            md.push_str(&format!(
                "- {} {} {} ({}): {}\n",
                e.date,
                e.commit.as_deref().unwrap_or("-"),
                e.warrant.as_deref().unwrap_or("-"),
                e.source.as_str(),
                e.why
            ));
        }
        md
    }

    /// Read an atom's Markdown.
    ///
    /// # Errors
    /// The line that does not read, by number.
    pub fn parse(text: &str) -> Result<Self, String> {
        let mut atom = Self::default();
        let mut lines = text.lines().enumerate();
        let Some((_, head)) = lines.next() else {
            return Err("the atom is empty".to_owned());
        };
        let path = head
            .strip_prefix("# Ledger: `")
            .and_then(|r| r.strip_suffix('`'))
            .ok_or_else(|| "line 1 is not `# Ledger: `<path>``".to_owned())?;
        atom.path = path.to_owned();
        for (n, line) in lines {
            let Some(rest) = line.strip_prefix("- ") else {
                continue;
            };
            let at = |why: &str| format!("line {}: {why}", n + 1);
            if let Some(e) = rest.strip_prefix("earlier: ") {
                if atom.earlier.is_some() || !atom.entries.is_empty() {
                    return Err(at("an `earlier` line comes once, before every entry"));
                }
                atom.earlier = Some(parse_earlier(e).map_err(|w| at(&w))?);
                continue;
            }
            atom.entries.push(parse_entry(rest).map_err(|w| at(&w))?);
        }
        Ok(atom)
    }

    /// Fold the oldest entries into `earlier` until the atom keeps `keep`
    /// entries, or (with a budget) fits it, keeping at least one.
    pub fn prune(&mut self, cfg: &Config) {
        match cfg.token_budget {
            Some(budget) => {
                while self.entries.len() > 1 && tokens(&self.render()) > budget {
                    self.fold(1);
                }
            }
            None => {
                if self.entries.len() > cfg.keep {
                    self.fold(self.entries.len() - cfg.keep);
                }
            }
        }
    }

    fn fold(&mut self, n: usize) {
        let folded: Vec<Entry> = self.entries.drain(..n).collect();
        let mut e = self.earlier.take().unwrap_or_default();
        let mut warrants: BTreeSet<String> = e.warrants.drain(..).collect();
        let mut texts: Vec<String> = if e.text.is_empty() {
            Vec::new()
        } else {
            vec![e.text.clone()]
        };
        for f in &folded {
            if e.count == 0 || f.date < e.first {
                e.first.clone_from(&f.date);
            }
            if e.count == 0 || f.date > e.last {
                e.last.clone_from(&f.date);
            }
            e.count += 1;
            if let Some(w) = &f.warrant {
                warrants.insert(w.clone());
            }
            if !texts.iter().any(|t| t.split(" | ").any(|x| x == f.why)) {
                texts.push(f.why.clone());
            }
        }
        e.warrants = warrants.into_iter().collect();
        e.text = cut(&texts.join(" | "), SUMMARY_TEXT_MAX);
        self.earlier = Some(e);
    }

    /// The JSONL line.
    #[must_use]
    pub fn line(&self, atom: &str) -> Line {
        Line {
            schema: LINE_SCHEMA.to_owned(),
            path: self.path.clone(),
            atom: atom.to_owned(),
            earlier: self.earlier.clone(),
            entries: self.entries.clone(),
        }
    }
}

/// About four characters a token: the estimate the budget is spent in.
#[must_use]
pub fn tokens(text: &str) -> usize {
    text.chars().count().div_ceil(4)
}

fn parse_earlier(s: &str) -> Result<Earlier, String> {
    let mut parts = s.splitn(3, "; ");
    let (Some(counts), Some(warrants), text) = (parts.next(), parts.next(), parts.next()) else {
        return Err(
            "an `earlier` line reads `<n> change(s), <first>..<last>; Warrants <ids>; <why>`"
                .to_owned(),
        );
    };
    let (n, range) = counts
        .split_once(" change(s), ")
        .ok_or_else(|| "`earlier` does not say `<n> change(s), <first>..<last>`".to_owned())?;
    let (first, last) = range
        .split_once("..")
        .ok_or_else(|| "`earlier` has no `<first>..<last>` dates".to_owned())?;
    let count = n
        .parse()
        .map_err(|_| format!("`earlier` count {n:?} is not a number"))?;
    let ws = warrants
        .strip_prefix("Warrants ")
        .ok_or_else(|| "`earlier` does not name its `Warrants`".to_owned())?;
    Ok(Earlier {
        count,
        first: date(first)?,
        last: date(last)?,
        warrants: if ws == "none" {
            Vec::new()
        } else {
            ws.split(", ").map(str::to_owned).collect()
        },
        text: text.unwrap_or_default().to_owned(),
    })
}

fn date(s: &str) -> Result<String, String> {
    chrono::NaiveDate::parse_from_str(s, "%Y-%m-%d")
        .map(|_| s.to_owned())
        .map_err(|_| format!("{s:?} is not a date (YYYY-MM-DD)"))
}

fn parse_entry(s: &str) -> Result<Entry, String> {
    const SHAPE: &str = "an entry reads `<YYYY-MM-DD> <commit|-> <warrant|-> (<source>): <why>`";
    let (head, why) = s.split_once("): ").ok_or_else(|| SHAPE.to_owned())?;
    let (fields, source) = head.split_once(" (").ok_or_else(|| SHAPE.to_owned())?;
    let mut f = fields.split(' ');
    let (Some(d), Some(c), Some(w), None) = (f.next(), f.next(), f.next(), f.next()) else {
        return Err(SHAPE.to_owned());
    };
    let source = Source::parse(source).ok_or_else(|| {
        format!("source {source:?} is not commit, deterministic, agent, agent-trace or git-ai")
    })?;
    if c != "-" && !(c.len() >= 7 && c.len() <= 64 && c.chars().all(|x| x.is_ascii_hexdigit())) {
        return Err(format!("{c:?} is not a commit id"));
    }
    if why.trim().is_empty() {
        return Err("the why is empty".to_owned());
    }
    Ok(Entry {
        date: date(d)?,
        commit: (c != "-").then(|| c.to_owned()),
        warrant: (w != "-").then(|| w.to_owned()),
        source,
        why: why.to_owned(),
    })
}

/// The ledger dir, absolute.
#[must_use]
pub fn dir(repo: &Repository, cfg: &Config) -> Utf8PathBuf {
    repo.root.join(&cfg.dir)
}

/// The atom path for a file.
#[must_use]
pub fn atom_path(repo: &Repository, cfg: &Config, file: &str) -> Utf8PathBuf {
    dir(repo, cfg).join(format!("{file}.md"))
}

/// Whether `file` is one the ledger never records: its own atoms, a
/// generated projection, `war`'s runtime state, and (scoped) the Warrant
/// and ticket records.
#[must_use]
pub fn excluded(cfg: &Config, file: &str) -> bool {
    file.starts_with(&format!("{}/", cfg.dir))
        || file.starts_with(".openwarrant/")
        || file.split('/').any(|p| p == "generated")
        || cfg
            .skip
            .iter()
            .any(|d| !d.is_empty() && file.starts_with(&format!("{d}/")))
}

/// Every atom under the ledger dir: (repository-relative atom path, parsed).
#[must_use]
pub fn load_all(repo: &Repository, cfg: &Config) -> Vec<(String, Result<Atom, String>)> {
    let root = dir(repo, cfg);
    let mut out = Vec::new();
    let mut stack = vec![root];
    while let Some(d) = stack.pop() {
        let Ok(entries) = fs::read_dir_utf8(&d) else {
            continue;
        };
        for p in entries {
            if fs::is_dir(&p) {
                stack.push(p);
            } else if p.extension() == Some("md") {
                let rel = repo.relative(&p);
                let parsed = fs::read_to_string(&p)
                    .map_err(|e| e.to_string())
                    .and_then(|t| Atom::parse(&t));
                out.push((rel, parsed));
            }
        }
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

/// Read one file's atom, or an empty one.
///
/// # Errors
/// An atom on disk that does not read.
pub fn load(repo: &Repository, cfg: &Config, file: &str) -> Result<Atom, String> {
    let p = atom_path(repo, cfg, file);
    match fs::read_to_string(&p) {
        Ok(t) => Atom::parse(&t).map_err(|e| format!("{}: {e}", repo.relative(&p))),
        Err(_) => Ok(Atom {
            path: file.to_owned(),
            ..Atom::default()
        }),
    }
}

/// Write one atom, creating its directories.
///
/// # Errors
/// The write.
pub fn store(repo: &Repository, cfg: &Config, atom: &Atom) -> Result<bool, RepoError> {
    let p = atom_path(repo, cfg, &atom.path);
    let text = atom.render();
    if fs::read_to_string(&p).ok().as_deref() == Some(text.as_str()) {
        return Ok(false);
    }
    if let Some(parent) = p.parent() {
        fs::create_dir_all(parent).map_err(|source| RepoError::Io {
            context: format!("could not create {parent}"),
            source,
        })?;
    }
    fs::write(&p, text).map_err(|source| RepoError::Io {
        context: format!("could not write {p}"),
        source,
    })?;
    Ok(true)
}

/// Add `entry` to `file`'s atom unless the atom already holds that commit's
/// entry, fold, and write. Whether anything was written.
///
/// # Errors
/// An atom that does not read, or the write.
pub fn add(
    repo: &Repository,
    cfg: &Config,
    file: &str,
    entry: Entry,
) -> Result<bool, Box<dyn std::error::Error>> {
    let mut atom = load(repo, cfg, file)?;
    let dup = atom.entries.iter().any(|e| {
        e.commit.is_some() && e.commit == entry.commit
            || e.commit.is_none() && entry.commit.is_none() && e.why == entry.why
    });
    if dup {
        return Ok(false);
    }
    atom.entries.push(entry);
    atom.prune(cfg);
    Ok(store(repo, cfg, &atom)?)
}

// ---- the compiled form ------------------------------------------------------------

/// `.openwarrant/ledger.jsonl`'s bytes: one line per readable atom, by path.
#[must_use]
pub fn jsonl(repo: &Repository, cfg: &Config) -> String {
    let mut out = String::new();
    for (rel, atom) in load_all(repo, cfg) {
        if let Ok(a) = atom
            && let Ok(s) = serde_json::to_string(&a.line(&rel))
        {
            out.push_str(&s);
            out.push('\n');
        }
    }
    out
}

/// Make `.openwarrant/` ignore what `war admin compile` writes there,
/// whatever the repository's own `.gitignore` says. The file ignores itself.
///
/// # Errors
/// The write.
pub fn ensure_ignored(root: &Utf8Path) -> Result<(), RepoError> {
    let d = root.join(".openwarrant");
    fs::create_dir_all(&d).map_err(|source| RepoError::Io {
        context: format!("could not create {d}"),
        source,
    })?;
    let p = d.join(".gitignore");
    let have = fs::read_to_string(&p).unwrap_or_default();
    let mut lines: Vec<&str> = have.lines().collect();
    let mut changed = have.is_empty();
    if have.is_empty() {
        lines.push("# war admin compile writes these: regenerated, never committed (M17).");
    }
    for want in IGNORED.iter().copied().chain([".gitignore"]) {
        if !lines.contains(&want) {
            lines.push(want);
            changed = true;
        }
    }
    if changed {
        fs::write(&p, format!("{}\n", lines.join("\n"))).map_err(|source| RepoError::Io {
            context: format!("could not write {p}"),
            source,
        })?;
    }
    Ok(())
}

/// Write `.openwarrant/ledger.jsonl` when the repository keeps a ledger (or
/// had one compiled). The path, when its bytes changed.
///
/// # Errors
/// A write.
pub fn compile(repo: &Repository) -> Result<Option<Utf8PathBuf>, RepoError> {
    let cfg = Config::read(&repo.root).unwrap_or_default();
    let target = repo.root.join(JSONL);
    if !fs::is_dir(dir(repo, &cfg)) && !fs::is_file(&target) {
        return Ok(None);
    }
    ensure_ignored(&repo.root)?;
    let text = jsonl(repo, &cfg);
    if fs::read_to_string(&target).ok().as_deref() == Some(text.as_str()) {
        return Ok(None);
    }
    fs::write(&target, text).map_err(|source| RepoError::Io {
        context: format!("could not write {target}"),
        source,
    })?;
    Ok(Some(target))
}

/// `war check`'s ledger findings: the table, each atom, and the JSONL never
/// tracked by git.
pub fn check(repo: &Repository, report: &mut Report) {
    let cfg = match Config::read(&repo.root) {
        Ok(c) => c,
        Err(e) => {
            report.push(Diagnostic::error(
                "ledger.config",
                crate::init::CONFIG_FILE.to_owned(),
                e,
            ));
            return;
        }
    };
    for (rel, atom) in load_all(repo, &cfg) {
        match atom {
            Err(e) => report.push(Diagnostic::error(
                "ledger.atom",
                rel,
                format!(
                    "this ledger atom does not read ({e}); fix the line, or rewrite the atom with \
                     `war admin ledger prune`"
                ),
            )),
            Ok(a) => {
                let want = format!("{}/{}.md", cfg.dir, a.path);
                if want != rel {
                    report.push(Diagnostic::error(
                        "ledger.atom",
                        rel.clone(),
                        format!("this atom names `{}`, whose atom is `{want}`", a.path),
                    ));
                }
            }
        }
    }
    if crate::vfs::is_hosted() {
        return;
    }
    let tracked = git(&repo.root, &["ls-files", "--", JSONL]);
    if tracked.ok && !tracked.stdout.trim().is_empty() {
        report.push(Diagnostic::error(
            "ledger.committed",
            JSONL.to_owned(),
            format!(
                "{JSONL} is committed. It is regenerated by `war admin compile` and is never a \
                 source: untrack it with `git rm --cached {JSONL}`; the atoms under {}/ are \
                 the record",
                cfg.dir
            ),
        ));
    }
}

// ---- writing entries from commits ---------------------------------------------------

/// One commit, as the writer reads it.
#[derive(Debug, Clone)]
pub struct Commit {
    pub sha: String,
    pub date: String,
    pub subject: String,
    pub body: String,
    pub files: Vec<String>,
}

/// The value of every `<key>:` trailer-style line in `text`.
#[must_use]
pub fn trailer(text: &str, key: &str) -> Vec<String> {
    text.lines()
        .filter_map(|l| {
            let (k, v) = l.trim().split_once(':')?;
            (k.trim().eq_ignore_ascii_case(key) && !v.trim().is_empty())
                .then(|| v.trim().to_owned())
        })
        .collect()
}

/// The body's first paragraph that is not a trailer block.
fn body_summary(body: &str) -> Option<String> {
    body.split("\n\n")
        .map(str::trim)
        .find(|p| {
            !p.is_empty()
                && !p.lines().all(|l| {
                    l.split_once(':').is_some_and(|(k, _)| {
                        !k.is_empty()
                            && k.len() <= 40
                            && k.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
                    })
                })
        })
        .map(|p| one_line(p, WHY_MAX))
}

/// Read one commit: date, subject, body, and the files it changed (added,
/// modified, renamed; never a deletion), the ledger's own excluded.
///
/// # Errors
/// git's answer.
pub fn read_commit(root: &Utf8Path, cfg: &Config, rev: &str) -> Result<Commit, String> {
    let r = git(
        root,
        &["show", "-s", "--format=%H%x1f%cs%x1f%s%x1f%b", rev, "--"],
    );
    if !r.ok {
        return Err(format!("git could not read {rev:?}: {}", r.why()));
    }
    let mut f = r.stdout.splitn(4, '\u{1f}');
    let sha = f.next().unwrap_or_default().trim().to_owned();
    let date = f.next().unwrap_or_default().to_owned();
    let subject = f.next().unwrap_or_default().to_owned();
    let body = f.next().unwrap_or_default().trim_end().to_owned();
    let d = git(
        root,
        &[
            "diff-tree",
            "--no-commit-id",
            "--name-only",
            "-r",
            "--root",
            "--diff-filter=d",
            "-z",
            &sha,
        ],
    );
    if !d.ok {
        return Err(format!("git could not list {sha}'s files: {}", d.why()));
    }
    let files = d
        .stdout
        .split('\0')
        .filter(|p| !p.is_empty() && !excluded(cfg, p))
        .map(str::to_owned)
        .collect();
    Ok(Commit {
        sha,
        date,
        subject,
        body,
        files,
    })
}

/// Every Warrant id this repository holds, with its title: directory
/// Warrants by `local_alias`, light ones by id.
#[must_use]
pub fn warrant_titles(repo: &Repository) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    for d in repo.warrant_dirs().unwrap_or_default() {
        let Ok(t) = fs::read_to_string(d.join("manifest.toml")) else {
            continue;
        };
        let Ok(m) = t.parse::<toml::Table>() else {
            continue;
        };
        if let Some(a) = m.get("local_alias").and_then(|v| v.as_str()) {
            let title = m.get("title").and_then(|v| v.as_str()).unwrap_or_default();
            out.insert(a.to_owned(), title.to_owned());
        }
    }
    if let Ok(store) = crate::ticket::Store::open(repo, None)
        && let Ok((tickets, _)) = store.load_all()
    {
        for t in tickets {
            out.insert(t.id().to_owned(), t.manifest.title.clone());
        }
    }
    out
}

/// The first Warrant `message` cites (`Warrant:` trailer) that this
/// repository holds.
#[must_use]
pub fn cited_warrant(message: &str, known: &BTreeMap<String, String>) -> Option<String> {
    crate::pr_gate::cited_in(message)
        .into_iter()
        .find(|id| known.contains_key(id))
}

/// The why for `file` in `commit`, by `mode`, and where it came from.
/// `None` in agent mode with no text: the agent is asked.
#[must_use]
pub fn why_for(
    mode: Mode,
    commit: &Commit,
    file: &str,
    warrant: Option<&str>,
    known: &BTreeMap<String, String>,
    agent: Option<&str>,
) -> Option<(Source, String)> {
    let deterministic = || {
        let w = warrant
            .and_then(|w| known.get(w))
            .filter(|t| !t.trim().is_empty());
        (
            Source::Deterministic,
            one_line(w.map_or(commit.subject.as_str(), String::as_str), WHY_MAX),
        )
    };
    match mode {
        Mode::Agent => agent
            .filter(|a| !a.trim().is_empty())
            .map(|a| (Source::Agent, one_line(a, WHY_MAX))),
        Mode::Deterministic => Some(deterministic()),
        Mode::Commit => {
            let trailers = trailer(&commit.body, "ledger");
            // `Ledger: <path>: <why>` speaks for one file; a plain one for all.
            let own: Vec<&str> = trailers
                .iter()
                .filter_map(|t| t.strip_prefix(file)?.strip_prefix(':').map(str::trim))
                .collect();
            let general: Vec<&str> = trailers
                .iter()
                .filter(|t| !commit.files.iter().any(|f| t.starts_with(&format!("{f}:"))))
                .map(String::as_str)
                .collect();
            let chosen = if own.is_empty() { general } else { own };
            if !chosen.is_empty() {
                return Some((Source::Commit, one_line(&chosen.join("; "), WHY_MAX)));
            }
            Some(
                body_summary(&commit.body)
                    .map(|b| (Source::Commit, b))
                    .unwrap_or_else(deterministic),
            )
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(d: &str, c: &str, why: &str) -> Entry {
        Entry {
            date: d.to_owned(),
            commit: Some(c.to_owned()),
            warrant: Some("t-abcd".to_owned()),
            source: Source::Commit,
            why: why.to_owned(),
        }
    }

    #[test]
    fn an_atom_round_trips_and_pruning_keeps_exactly_n_plus_a_summary() {
        let mut a = Atom {
            path: "src/x.rs".to_owned(),
            earlier: None,
            entries: (1..=5)
                .map(|i| {
                    entry(
                        &format!("2026-01-0{i}"),
                        &format!("{i:0>40}"),
                        &format!("why {i}"),
                    )
                })
                .collect(),
        };
        a.prune(&Config::default());
        assert_eq!(a.entries.len(), 3);
        let e = a.earlier.clone().expect("summary");
        assert_eq!(
            (e.count, e.first.as_str(), e.last.as_str()),
            (2, "2026-01-01", "2026-01-02")
        );
        assert_eq!(e.text, "why 1 | why 2");
        let back = Atom::parse(&a.render()).expect("parses");
        assert_eq!(back, a);
        // Folding again adds to the summary rather than replacing it.
        a.entries
            .push(entry("2026-01-09", &"9".repeat(40), "why 9"));
        a.prune(&Config::default());
        assert_eq!(a.entries.len(), 3);
        assert_eq!(a.earlier.as_ref().map(|e| e.count), Some(3));
    }

    #[test]
    fn a_token_budget_folds_until_the_atom_fits_and_keeps_one() {
        let mut a = Atom {
            path: "a".to_owned(),
            earlier: None,
            entries: (1..=6)
                .map(|i| entry("2026-02-01", &format!("{i:0>40}"), &"w".repeat(80)))
                .collect(),
        };
        let cfg = Config {
            token_budget: Some(1),
            ..Config::default()
        };
        a.prune(&cfg);
        assert_eq!(a.entries.len(), 1, "never below one entry");
        let cfg = Config {
            token_budget: Some(10_000),
            ..Config::default()
        };
        let mut b = Atom {
            path: "a".to_owned(),
            earlier: None,
            entries: vec![entry("2026-02-01", &"1".repeat(40), "x"); 6],
        };
        b.prune(&cfg);
        assert_eq!(b.entries.len(), 6, "a budget that fits folds nothing");
    }

    #[test]
    fn a_malformed_line_and_a_bad_table_are_refused() {
        assert!(Atom::parse("# Ledger: `a`\n\n- yesterday - - (commit): x\n").is_err());
        assert!(Atom::parse("# Ledger: `a`\n\n- 2026-01-01 - - (rumour): x\n").is_err());
        assert!(Atom::parse("# nope\n").is_err());
        assert!(Config::from_text("[ledger]\nkeep = 0\n").is_err());
        assert!(Config::from_text("[ledger]\nmode = \"vibes\"\n").is_err());
        assert!(Config::from_text("[ledger]\ntoken_budget = 0\n").is_err());
        assert!(Config::from_text("[ledger]\nkeeep = 2\n").is_err());
        let c = Config::from_text("[ledger]\nkeep = 5\nmode = \"agent\"\n").unwrap();
        assert_eq!((c.keep, c.mode), (5, Mode::Agent));
    }

    #[test]
    fn the_commit_mode_reads_a_trailer_then_the_body_then_falls_back() {
        let known: BTreeMap<String, String> =
            [("t-abcd".to_owned(), "Fix the login redirect".to_owned())].into();
        let mut c = Commit {
            sha: "a".repeat(40),
            date: "2026-01-01".to_owned(),
            subject: "subject line".to_owned(),
            body: "Ledger: src/a.rs: the redirect read the wrong cookie\nLedger: tidy up\nWarrant: t-abcd"
                .to_owned(),
            files: vec!["src/a.rs".to_owned(), "src/b.rs".to_owned()],
        };
        let w = Some("t-abcd");
        assert_eq!(
            why_for(Mode::Commit, &c, "src/a.rs", w, &known, None)
                .unwrap()
                .1,
            "the redirect read the wrong cookie"
        );
        assert_eq!(
            why_for(Mode::Commit, &c, "src/b.rs", w, &known, None)
                .unwrap()
                .1,
            "tidy up"
        );
        c.body = "The cookie was read before the session.\n\nWarrant: t-abcd".to_owned();
        assert_eq!(
            why_for(Mode::Commit, &c, "src/b.rs", w, &known, None).unwrap(),
            (
                Source::Commit,
                "The cookie was read before the session.".to_owned()
            )
        );
        c.body = "Warrant: t-abcd".to_owned();
        assert_eq!(
            why_for(Mode::Commit, &c, "src/b.rs", w, &known, None).unwrap(),
            (Source::Deterministic, "Fix the login redirect".to_owned())
        );
        assert_eq!(
            why_for(Mode::Deterministic, &c, "x", None, &known, None)
                .unwrap()
                .1,
            "subject line"
        );
        assert!(why_for(Mode::Agent, &c, "x", None, &known, None).is_none());
    }
}
